### ISSUE TITLE
Module object empty when proxyquiring?

### ISSUE THREAD

**Issue by jakemmarsh** [thlorenz/proxyquire#103]
I'm using proxyquire to import a file like so for testing:

```js
function httpStub() {
  return {
    withCredentials: () => {
      return { end: () => {} };
    }
  };
}

const PlaylistAPI = proxyquire('../../app/js/utils/PlaylistAPI', { 
   request: {
     get: httpStub,
     put: httpStub,
     patch: httpStub,
     post: httpStub,
     del: httpStub,
     '@global': true
   }
});

// PlaylistAPI = {} here
```

And `PlaylistAPI` has a structure like this:

```js
import APIUtils from './APIUtils';

var PlaylistAPI = {
  get(slug) {
    return APIUtils.get('playlist/' + slug);
  }
};

export default PlaylistAPI;
```

However, this results in `PlaylistAPI` being an empty object in my test file after proxyquiring. If I require the same path normally (or via es6 import), it is defined as it should be. I've also placed a `console.log` to ensure the `PlaylistAPI` file is actually being loaded/executed, and it is.

Any ideas why this would result in an empty object?

**Comment by bendrucker** [comment]
Can you upload a reproduction/example so I can run it?

**Comment by jakemmarsh** [comment]
Closing, as I'm no longer using proxyquire.
