### ISSUE TITLE
Possible to stub constructors?

### ISSUE THREAD

**Issue by trueblue2704** [thlorenz/proxyquire#104]
I have this module that I need to mock.

`var dynasty = require('dynasty')(config);`

It takes in the configuration parameters as a constructor. Is there any way I can pass this in with the stub?

`var users = proxyquire('../models/users.js', { 'dynasty' : dynastyStub });`

If I try doing this, then I get an TypeError saying require(...) is not a function.

**Comment by bendrucker** [comment]
Sure, just declare your test config in your tests if needed and then replace `dynasty` with a function that behaves identically and constructs a model.
