### ISSUE TITLE
Allow overriding properties in stub objects

### ISSUE THREAD

**Issue by devinus** [thlorenz/proxyquire#105]
```js
var stub = {
  someFunc: sinon.spy(function(callback) {
    callback(null, 'foo');
  })
};

var User = proxyquire('../../lib/models/user', {
  'somelib': stub
});

stub.someFunc = sinon.spy(function(callback) {
  callback(new Error());
});
```

The second function never gets called. It's like proxyquire is deep cloning the object or something.

**Comment by bendrucker** [comment]
Yes, proxyquire copies over stub values via https://www.npmjs.com/package/fill-keys. This is important to other features/users, so no possibility of removing the behavior. Best to re-proxyquire when you change the stubs.
