### ISSUE TITLE
Problem with private Npm modules

### ISSUE THREAD

**Issue by guyellis** [thlorenz/proxyquire#106]
I'm trying to use proxyquire with a private Npm module. I have:

```js
const myModule = proxyquire('../lib/my-module', {
  '@mycompany/my-private-module': myStub
});
```

The call to `proxyquire()` dies at `Module._resolveFilename(path, module);` which at the time of writing this is here: https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L215

At that point it stops. No error is printed.

My suspicion is that it can't resolve `@mycompany/my-private-module`

Any ideas on how to use private modules with proxyquire or what I'm doing wrong?

**Comment by gyandeeps** [comment]
I know I have used `proxyquire` for private package before, here is the example: https://github.com/eslint/eslint/blob/v1.4.3/tests/lib/config.js#L592

Maybe more information is need on how you are doing this?

**Comment by guyellis** [comment]
@gyandeeps am trying to work out what else I can provide.

The target module ('../lib/my-module') also has async as a requirement.

If I swap out `@mycompany/my-private-module` with `async` then it "works fine" - i.e. proxyquire doesn't stop at that point and async is proxied.

**Comment by bendrucker** [comment]
Definitely going to need something I can clone and reproduce. FWIW we're talking about scoped packages here, not private ones. Should be reproducible without sharing that specific package if the scoping is the issue.

**Comment by guyellis** [comment]
Thanks @gyandeeps and @bendrucker for entertaining this issue. Turned out to be that the stub didn't have a function that `../lib/my-module` needed which was causing it to blow-up at that point.
