### ISSUE TITLE
Using proxyquire with native dependencies (with `.node` files)

### ISSUE THREAD

**Issue by hsablonniere** [thlorenz/proxyquire#108]
Hi maintainers :smile:

I'm trying to use **proxyquire** with an app using [couchbase](https://www.npmjs.com/package/couchbase). This module has some native dependencies (with `.node` files).

I have some **mocha** tests where I don't stub the couchbase module. Because I used `@global` on some stubs, this trigger the big cache clear, which is exactly what I want.

From the tests I've done, this _"clean"_ seems too agressive. When using mocha in watch mode, the first run goes well and the others fail. It seems that clearing the cache the ways you do [here](https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L205) tells Node that he should require the couchebase module again but when he transitively requires the other files and tries to require a `.node` it throws with this :

```
Error: Module did not self-register.
```

You can see the problem with a simple execution of this code :

``` js
var Module = require('module');

require('couchbase');

Module._cache = {};

require('couchbase');

// => Error: Module did not self-register.
```

With a naive cleaning that does not remove the `.node` files. It does not fail.

``` js
var Module = require('module');

require('couchbase');

for (var id in Module._cache) {
    if (!id.match(/.node$/)) {
        delete Module._cache[id];
    }
}

require('couchbase');

// => no error, everything is OK
```

I'm not sure this would be the best way to fix this problem, so before submiting a PR I wanted your opinion.

Cheers :heart:

**Comment by bendrucker** [comment]
Honestly not sure, your solution seems as good as anything I can think of

**Comment by hsablonniere** [comment]
OK. I'll try to find out more on have the `_cache` works and I'll submit a PR :wink:

**Comment by hsablonniere** [comment]
I found these :

* https://github.com/nodejs/node/issues/5016
* https://github.com/request/request-promise/issues/89

It seems that as of right now, native addons that are *Not multi-context ready* (which I don't really understand) cannot be unregistered easily.

Since your lib does not allow to stub such native addons, I would say it's OK to only remove stuffs that are not `.node`.

**Comment by hsablonniere** [comment]
Err... I saw in the test suite that you check that `.node` file can be stubbed. Is it a problem ?
