### ISSUE TITLE
how do I prevent side effects from occuring?

### ISSUE THREAD

**Issue by yoshuawuyts** [thlorenz/proxyquire#110]
Hey, I'd like fully stub out a module and squash all side effects. How do I do this? Thanks!

## repro
__derp.js__
```js
(function () {console.log('failure')})()
```
__darp.js__
```js
function stub () {}
stub['@global'] = true
require('proxyquire')('./darp', stub)
````

## expected
```sh
$ node darp.js
success!
```

## actual
```sh
$ node darp.js
failure
```

**Comment by yoshuawuyts** [comment]
ah, so found it ~~~ ~~~
```js
function stub () {}
stub['@global'] = true
require('proxyquire').noCallThru('./darp', stub)
```

**Comment by yoshuawuyts** [comment]
Alright, so I haven't fixed it :(
__derp.js__
```js
function stub () { console.log( 'hello' )}
stub['@global'] = true
stub['@runtimeGlobal'] = true
require('proxyquire').noCallThru('velocity-animate', stub)
require('./darp')()
```
__darp.js__
```js
const foo = require('velocity-animate')

module.exports = function () {
  foo()
}
```
__velocity-animate__
where `velocity-animate` kinda does this:
```js
(function () {})(window)
// can't find window, cause we're in node
```
---
In this case `velocity-animate` still causes side effects when called - which should definitely not be happening. Am I missing anything?

**Comment by bendrucker** [comment]
`noCallThru` doesn't take args. Try calling it first or just assign `stub['@noCallThru'] = true`.

**Comment by yoshuawuyts** [comment]
Still doesn't work :(
```js
function stub () { console.log( 'hello' )}
stub['@global'] = true
stub['@runtimeGlobal'] = true
stub['@noCallThru'] = true
require('proxyquire')('velocity-animate', stub)
require('./darp')()
```

**Comment by bendrucker** [comment]
Ah, now I think I see what you're trying to do. In order to stub velocity-animate globally, you basically just globally proxyquire a module that requires velocity-animate rather than trying to do velocity-animate itself. I think that'll work.

**Comment by yoshuawuyts** [comment]
Ah, alright - not the answer I was expecting, but it works for me! Thanks heaps :sparkles:

**Comment by bendrucker** [comment]
No prob -- proxyquire is designed to stub B when A requires B. Stubbing B directly is basically an accidental feature. Best bet here if possible is probably to publish something like this:

```js
module.exports = process.browser ? require('velocity-animate') : shim
```

**Comment by yoshuawuyts** [comment]
hah, lol - but that would require proper considerations of how people might use code and we can't have that now, can we? `velocity.js` is a bloated mess; I'm happy to stub it locally for a client and keep poking fun at it for years to come :grin:
