### ISSUE TITLE
What if the module I want to stub is just a function?

### ISSUE THREAD

**Issue by callumlocke** [thlorenz/proxyquire#113]
The docs seem to talk only about cases where you want to stub individual keys of a module. What about if I want to stub the whole module, because the whole module is just one function?

For example, [pify](https://github.com/sindresorhus/pify) is just a function:

```js
var pify = require('pify');
pify(...);
```

If I proxyquire a module that uses pify, can I stub its pify with my own replacement function? I'm hoping this is possible, but there's no mention of this kind of use case in the docs (unless I've missed it).

**Comment by bendrucker** [comment]
Yup, totally cool to just put `proxyquire('./my-module', {pify: myPify})`.

**Comment by callumlocke** [comment]
Oh awesome, I wasn't expecting to hear that. From the readme, all the call-thru stuff, I seemed to me like proxyquire was entirely designed around stubbing individual keys, so I just assumed if I passed a function in then nothing would get stubbed as there are no keys. It might be worth adding a mention of this to the readme

**Comment by kromol** [comment]
This approach does not work if dependency is relative - e.g.  starts from dot: 
`const module = require('./my-module')`;
It throws `Cannot find module` error

**Comment by bendrucker** [comment]
Not true, your module must exist unless you enable `noCallThru`. Please open a new issue if you need support.
