### ISSUE TITLE
load es6 object

### ISSUE THREAD

**Issue by hcastellonLan** [thlorenz/proxyquire#114]
Hello

i have problems loading the es6 object with proxyquire

i have this class

```js
import BookingClient from "../clients/booking"
class Booking {
  constructor() {
   }
  get(recordLocator, lastName) {
    let bookingClient = new BookingClient();
    return bookingClient.get(recordLocator, lastName);
  }
}
module.exports = {
    Booking: Booking
};
```

And the dependency

```js
import restify from "restify"
class Booking {
  constructor() {
	}
  get(recordLocator, lastame) {
   
  }
}
module.exports = {
    Booking: Booking
};
```

My Test 

```js
it("should call a api booking and obtain a booking", (done) =>{

    let bookingStub = {
      get: (recordLocator, lastName) => {
        return "hello"
      }
    }
    let Booking = proxyquire("../../src/controllers/booking", {
      "../clients/booking":bookingStub
    });
    let bookingController = new Booking();
    let x = bookingController.get("AAAAAA", "lastame")
  });
```

The problem is than i obtain this message "TypeError: object is not a function" in this line " `let bookingController = new Booking();`

i cheked the path and is ok

Exist a problem using babel with class and objects with proxyquire? or other problem than i can't see?

Thank you very much

**Comment by bendrucker** [comment]
Please highlight your code in the future. 

Throw the `class` keyword away for now, it's just a distraction here. You started with this:

```js
function Booking () {}

function Booking.get = function get () {}
```

And then you're trying to stub it with:

```js
{get: function () {}}
```

Then you try to call `bookingStub` as a function with `new` and it fails. Make `bookingStub` a function and *then* append your `get` method.

**Comment by tuto** [comment]
thank you very much
 sorry by the highlight

**Comment by tuto** [comment]
@bendrucker 

i tested the solution but for me is fail again 
`let bookingStub = () => {};
    bookingStub.get = (recordLocator, lastame) => {
        console.log("DFDSFSD")
        return new Promise((resolve) => {
          resolve(bookingResult);
        });
      }

    let Booking = proxyquire("../../src/controllers/booking", {
      "../clients/booking":bookingStub
    });

    let bookingController = new Booking();`

and the result si the same

`TypeError: object is not a function`

any idea?

**Comment by bendrucker** [comment]
`Booking.Booking` would be your constructor since you're nesting under that key
