### ISSUE TITLE
possible es2015 issues

### ISSUE THREAD

**Issue by scaljeri** [thlorenz/proxyquire#115]
I'm trying to setup a simple test with proxyquire, but whatever I do it doesn't work

Here is a [repo](https://github.com/scaljeri/mock-require/tree/proxyquire) to reproduce.

main.js:

    import proxyquire from 'proxyquire';

    let bar = proxyquire('./bar', { './foo': () => {
        return 1;
    }} );
    console.log(bar());

bar.js:

     import foo from './foo';

     function bar() {
         return foo();
    }
    export default bar;

foo.js:

    function foo() {
        return Math.random();
    }
    export default foo;

And when I run this:

    $> ./node_modules/.bin/babel-node main.js
    /Usersdev/tmp/mock/main.js:13
    console.log(bar());
                ^

    TypeError: bar is not a function
        at Object.<anonymous> (main.js:7:13)
        at Module._compile (module.js:413:34)
        ...

Does this has anything todo with es2015 or is it just me ?

**Comment by NullDivision** [comment]
`import foo from './foo'` equates to `{default: function foo}`.

To stub it you need to do:

```
let bar = proxyquire(
    './bar',
    {
        './foo': {
            default: () => {
                return 1;
            }
        }
    }
);
```

**Comment by bendrucker** [comment]
Ah, good call! I vaguely remember Babel having a setting for `export default --> module.exports` but it's been more than a year since I've touched it.

**Comment by jseminck** [comment]
Is this documented somewhere?

I also couldn't get `proxyquire` to work with import/export syntax and was almost thinking to revert back to using `require()` syntax because of it. Luckily stumbled upon this thread and this solution works like a charm. (well thinking about it afterwards, it completely makes sense).

**Comment by thlorenz** [comment]
@jseminck we'll be happy to add some such section to the Readme.
Could you please provide that addition via a PR?
Thanks

**Comment by jseminck** [comment]
Sure. I'll try to write something about it with the example from above. Not the best technical writer though. :)

**Comment by Astridax** [comment]
For reference to anyone else looking this is the plugin required to do this:
https://www.npmjs.com/package/babel-plugin-add-module-exports

Source of info: 
http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
