### ISSUE TITLE
Cannot find module 'module'

### ISSUE THREAD

**Issue by minfawang** [thlorenz/proxyquire#116]
I'm trying to use wallaby to do unit tests with this library, and when I do:
~~~javascript
import proxyquire from 'proxyquire';
~~~

It gives me the following error:
~~~
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'module' in /project_root/node_modules/proxyquire/lib
~~~

It might be my setup of wallaby is incorrect, but I have used to require other node modules that worked just fine. Any idea of why this error is thrown?

Thanks!!

**Comment by bendrucker** [comment]
I'd ping Wallabay about this. Not idea what their runtime is like but they'd have to fix this on their end.

**Comment by brendan-roche** [comment]
This issue was closed, but what was the resolution for this? 

I'm hitting this issue now too.
