### ISSUE TITLE
Module object import gets wrapped in default

### ISSUE THREAD

**Issue by NullDivision** [thlorenz/proxyquire#117]
I tried stubbing a module using the object import syntax and noCallThru (though without noCallThru it only works because the method gets called) and here's the issue:

Unit under test
```javascript
import * as baz from 'baz';

export function test() {
    console.log(baz);
    console.log(baz.a(), baz.b());
}
```

Module:

```javascript
export function a() {return 1;}
export function b() {return 2;}
```

Test file:
```javascript
let bazStub = {};
let foo = proxyquire.noCallThru()('./bar', {'./baz': bazStub}).test

bazStub.a = () => 3;
bazStub.b = () => 4;

foo();
// {default: {a: [Function], b: [Function]}}
// Error: baz.a is not a function

let foo = proxyquire.noCallThru()('./bar', {'./baz': {a: () => 3, b: () => 4}}).test

foo();
// {a: [Function], b: [Function], default: {a: [Function], b: [Function]}}
// 3, 4
```

The actual code works fine and returns an object with props `a` and `b` but proxyquire doesn't resolve them correctly.

Update: With the deconstruct import `import {a, b} from './baz'` everything works as expected.

**Comment by bendrucker** [comment]
Sorry for the trouble but for now we're not going to provide support for transpiled module loading via Babel. It sucks that there are all these pitfalls but I don't have any advice to offer other than to comment that this sort of thing is why I dropped Babel and its shims in the first place.

**Comment by NullDivision** [comment]
I understand. Thank you for the quick response in any case. :)

**Comment by NullDivision** [comment]
To be clear, is it an architectural choice or a time constraint? Because if it's the latter I'd be willing to put in a bit of time for a PR.

**Comment by bendrucker** [comment]
Bit of both. Adding special handling for the Babel-generated code isn't something I'm willing to consider. The use of normal CommonJS is a core assumption in proxyquire. If and when `import` comes natively to Node that's a different story.

**Comment by thlorenz** [comment]
@NullDivision have a look at the code babel generates here, I think it's something like:

`export['default'] ... ` for functions, i.e. not `module.exports`. It should do something along the lines of `require('./the module').default` to import it then ... not entirely sure, but seen something similar.

You'd need you proxyquire use according to that.

So find the generated code for the exporting and importing modules and go from there. If you need feedback paste those snippets here so we can have a look.

**Comment by NullDivision** [comment]
If memory (and my tests) serves, `export['default']` only applies if you're doing explicit `export default function myFunc() {}`. Otherwise it uses the function's signature to determine the export property name.

**Comment by ChaseMoskal** [comment]
To stub a function on a default import/export, I successfully used the following:

    import utilities from "./utilities"

    const PaperclipMaximizer = proxyquire("./PaperclipMaximizer", {
      "./utilities": {
        default: Object.assign(Object.create(utilities), {

          // Stubbed function placed onto the default export.
          sum: (a, b) => a + b
        })
      }
    })

In this example, I am stubbing the `sum` function on the `utilities` module default export — *but just for my "PaperclipMaximizer" module, in this case*

  - `Object.assign` is used to mix in stubbed functions with the original ones on `utilities`
  - `Object.create` makes a new object which extends `utilities`
