### ISSUE TITLE
Multiple proxiquired stubs for the same dep

### ISSUE THREAD

**Issue by mkay581** [thlorenz/proxyquire#118]
Thanks a lot for creating this package. Unless I am missing something, I don't see any way to proxyquire (or stub) multiple instantiations of a class. Consider the following scenario:

```javascript
// carousel.js
import Panel from 'panel';
class Carousel {
     /**
     * When the carousel is instantiated.
     * @param {HTMLCollection|NodeList} panels - The panels elements to use for the carousel
     */ 
    constructor (panels) {
       this._panelInstance = {};
       for (var i; i < panels.length; i++) {
          this._panelInstance['panel' + i] = new Panel(panels[i]);
       }
  }
}
```

What would be the best way, using proxyquire, to stub the Panel's constructor to test that `new Panel()` was called with appropriate arguments when testing Carousel class?

I know I could proxyquire the Panel dependency for each call to `new Carousel()`, however what if I want to return different proxied stub for each individual `Panel` instance?

**Comment by bendrucker** [comment]
That kind of logic is up to you. Proxyquire doesn't care what your code does or what your modules look like. You could proxy `Panel` to return different results based on the input or based on a call index that you increment in your Panel stub. You could get even fancier and have an array of instances that you pre-create and then return from that array depending on the index. Entirely up to you.

**Comment by mkay581** [comment]
Ok thanks, was just wondering if there was some of sort of functionality in this package I was missing.
