### ISSUE TITLE
Not replacing const, require nor let.

### ISSUE THREAD

**Issue by nschurmann** [thlorenz/proxyquire#119]
This is my code:

```javascript
"use strict";
const schema_1 = require("../schema");
const dn = require("../lib/dn-helpers");
const u = require("../lib/utils");
const uuid = require('node-uuid');

exports.getBrand = (db, id) => {
    console.log('dn', dn);
    return dn.sGetH(db, schema_1.Brands, id);
};
```

and this is the test:
```javascript
const assert = require("assert")
const sinon = require("sinon")
const proxyquire = require("proxyquire")

describe("Brand", () => {
  describe("func: getBrand", () => {
    var spy, dnStub, brand
    
    it("calls simple get by hash `sGetH`", () => {
      spy = sinon.spy()
      dnStub = { sGetH: spy }
      brand = proxyquire(
        "../../modules/brand", { 'dn': dnStub, 'schema_1': { 'Brands': "brandsData" } })
      brand.getBrand({}, "hashedid")
    })
  })
})
```

The `console.log` prints out the content of the library instead of replacing it.
Also tried with `../lib/dn-helpers` with no result.

**Comment by nikcorg** [comment]
The keys in the object passed to proxyquire should be the _paths_ given to require, not the symbol they're assigned to, i.e. replace `{ 'dn': dnStub ...` with `{ '../lib/dn-helpers': dnStub ...` and it should work as expected.

**Comment by nschurmann** [comment]
Thanks @nikcorg , does this works also for replacing constants existing inside the file? like
```javascript
const fn1 = x => x
```

```javascript
var myMock = sinon.stub()
proxyquire('./myfile', { 'fn1': myMock })
```

**Comment by bendrucker** [comment]
You're missing the point. Proxyquire proxies require. It doesn't try to manipulate your code otherwise and our position is that variable manipulation is bad.

**Comment by nschurmann** [comment]
@bendrucker so, if i write a test for a function, then i write another test for another function that calls the prior function, is bad to change it to a spy and test that the function was called? Testing an existing function more than once is a bad practice, it may make your tests pass or fail in unwanted scenarios.

What is your approach in this scenario?

**Comment by bendrucker** [comment]
Not really sure what you mean, simplified code would be helpful

**Comment by nschurmann** [comment]
```javascript
const fn1 = x => x // this has it's own test.

// the following, i need to test that is calling fn1, but not actually call fn1.
export const fn2 = x => {
  fn1(x)
}

// this would be helpful
var spy = sinon.spy()
var file = proxyquire('./myfile', { fn1: spy})
file.fn2(2)
assert(spy.calledWith(2), 'fn1 was not called.')
```

**Comment by bendrucker** [comment]
You don't have a `require` statement anywhere in that code so proxyquire isn't relevant.

**Comment by nschurmann** [comment]
@bendrucker the question was `What is your approach in this scenario?`

**Comment by bendrucker** [comment]
Oh. I never replace functions directly. If a function implements enough behavior to justify replacement for a mock, I say it belongs in another module. At that point proxyquire can step in and proxy the complex function in your unit tests.
