### ISSUE TITLE
Commit 'Delete stubs from require cache when in noPreserveCache mode' breaks when using coffee script

### ISSUE THREAD

**Issue by liamqma** [thlorenz/proxyquire#124]
Hi maintainers :smile:

The recent [commit](https://github.com/thlorenz/proxyquire/commit/9602114688b95f33ec04a077796ab4e7bb5a8240) I think will break if using coffeescript along with  '_preserveCache' set to be true.

The following code will not be able to resolve .coffee 
```Javascript
var stubIds = Object.keys(stubs).map(function (stubPath) {
   return resolve.sync(stubPath, {
       basedir: dirname(id)
    })
});
```
Unless we explicitly set  extension to include .coffee based on [node-resolve docs](https://github.com/substack/node-resolve#resolveid-opts-cb)
```Javascript
var stubIds = Object.keys(stubs).map(function (stubPath) {
   return resolve.sync(stubPath, {
       basedir: dirname(id),
       extensions: [ '.js', '.coffee' ]
    })
});
```

Cheers :heart:

**Comment by bendrucker** [comment]
Ah, interesting. Related to #122 but should be way easier to solve. Appreciate you doing most of the work!

I think I should be able to grab `require.extensions` and that CoffeeScript will add itself there.
