### ISSUE TITLE
Using proxquire with jspm / SystemJS

### ISSUE THREAD

**Issue by screendriver** [thlorenz/proxyquire#125]
Is it possible to use proxyquire with [jspm](http://jspm.io) / [SystemJS](https://github.com/systemjs/systemjs) that runs in the browser? I tried a lot but I don't get it running.

**Comment by bendrucker** [comment]
See proxyquireify. That's the only option for the browser.

**Comment by screendriver** [comment]
Ok. Too bad. Browserify ist completely different to jspm / SystemJS.

**Comment by bendrucker** [comment]
Yup, that's the reason I still use and love Browserify versus other larger APIs like Webpack and entirely different conceptual tools like SystemJS. Browserify ships with the least and had an incredibly rich ecosystem of 3rd party tools, many of which are extremely mature.

**Comment by screendriver** [comment]
It depends 😁  I prefer technologies that are based on an industry standard [specification](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#august_24_2014_draft_rev_27) that are working without any compilation / transpilation steps right in the browser as if they would support it natively. So I have **not** to change any code / builds when the browsers are ready to support it natively. It just works without any modifications in the future 😉
