### ISSUE TITLE
NODE_PATH with proxyquire 1.7.5+

### ISSUE THREAD

**Issue by alif** [thlorenz/proxyquire#126]
Since v1.7.5 I've been getting module not found errors and I believe it's related to `NODE_PATH` and likely related to this change with using `node-resolve`:
https://github.com/thlorenz/proxyquire/compare/b624446b260fab0103b3cad339e6434858739589...4776b6958f7423d11b2504f6a2e1f32293dd74eb#diff-35740953abc60c3d609ae0fd6ce0f490R187

And it's most likely related to this issue in `node-resolve` - https://github.com/substack/node-resolve/issues/39

**Comment by bendrucker** [comment]
Check the latest, should fix it
