### ISSUE TITLE
Dependency path hasn't been resolved

### ISSUE THREAD

**Issue by tamtakoe** [thlorenz/proxyquire#129]
smth.js
```js
const utils = require('../utils/index');
//... module code
```

smth.test.js
```js
const smth = proxyquire('./modules/smth/index', {
    '../utils/index': utils
});
//... test code
```

It works. But if I change proxyquire dependency path for `'./../utils/index': utils` or `'../utils/../utils/index': utils` it doesn't work, because path hasn't been resolved

**Comment by bendrucker** [comment]
Proxyquire isn't doing anything fancy with your paths. It expects exact matches between your `require` calls and your stub objects.

https://github.com/thlorenz/proxyquire/blob/572b4c9b84c760462a0af47ba18cec27cfcec901/lib/proxyquire.js#L144

**Comment by tamtakoe** [comment]
It is strange, because node.js always resolves paths and a developer expects the same behavior from node.js modules.

The second strange thing that I encountered is merging native module with mock module. F.e. If I have

module.js
```js
module.exports = {a: 1, b: 1};
```
module.mock.js
```js
module.exports = {a: 2};
```
index.js
```js
var module = require('./module');
console.log(module);
```
index.test.js
```js
proxyquire('./index', {
    './module': require('./module.mock')
});
```

I will get in console:
```js
{a: 2, b: 1};
```

It is very strange behavior. Of course I will get error if module.js contains dependencies which can't be resolved with test framework. Every adequate developer expects that his mock will change particular dependency and original module will never be launched.

Unfortunately proxyquire can't be used for tests now :(
