### ISSUE TITLE
Proxyquire isn't preserving cache

### ISSUE THREAD

**Issue by KarlPurk** [thlorenz/proxyquire#133]
Has `preserveCache` regressed again?  I'm seeing some strange behaviour with `1.7.10`:  

**foo.js**

``` js
var count = 0;

module.exports = function() {
    return ++count;
};

```

**test.js**

``` js
var assert = require('assert');
var proxyquire = require('proxyquire').preserveCache();

var foo1 = proxyquire('./foo', {});
var foo2 = proxyquire('./foo', {});
var foo3 = proxyquire('./foo', {});

assert.equal(foo1(), 1);
assert.equal(foo2(), 2); // Fails here, because proxyquire isn't caching the module
assert.equal(foo3(), 3);
```

The above test fails on the second assertion because the cache isn't being preserved.  However if I just use require directly it works:

**request-test.js**

``` js
var assert = require('assert');
var proxyquire = require('proxyquire').preserveCache();

var foo1 = require('./foo');
var foo2 = require('./foo');
var foo3 = require('./foo');

assert.equal(foo1(), 1);
assert.equal(foo2(), 2);
assert.equal(foo3(), 3);
```

**Comment by thlorenz** [comment]
Could you please PR with a failing test (in the style all other tests are written)?
Contributors can then go from there and either figure out if the test is incorrect or fix proxyquire to make it pass.
Thanks.

**Comment by mutantcornholio** [comment]
I don't think that this testcase is correct.

I mean, how proxyquire would overwrite modules inside your module if it won't be executed again?

**Comment by bendrucker** [comment]
Cache behavior has changed significantly, closing due to age.
