### ISSUE TITLE
noCallThru makes it impossible to modify the stub

### ISSUE THREAD

**Issue by vitalybe** [thlorenz/proxyquire#135]
Consider the following test code. 

Running **test 1** on it works as expected and prints 1. However, **test 2** prints 1 as well. Removing `.noCallThru()` fixes this behavior and prints 2 for 2nd test. 

	var proxyquire = require('proxyquire').noCallThru();

	describe('Song', () => {

		let self = {};

		beforeEach(() => {

			// Mocks
			self.stubWrappedSoundManager = {
				loadSound: sinon.stub().returns(1);
			};

			// SUT
			let SongModule = proxyquire('../../app/stores/song.js', {
				'../utils/wrapped_sound_manager': self.stubWrappedSoundManager
			});

			self.Song = SongModule.Song;

		});

		it('test 1', () => {
			let song = new self.Song(generateMockSong(ARTIST, ALBUM, TITLE));
			song.testPrintLoadSound(); // Prints 1 as expected

		});

		it('test 2', () => {
			self.stubWrappedSoundManager.loadSound = sinon.stub().returns(2);

			let song = new self.Song(generateMockSong(ARTIST, ALBUM, TITLE));
			song.testPrintLoadSound(); // Still prints 1 :(
		});

	});

Is this a bug? If not, how else can I change a stub in a test when **noCallThru** exists?

**Comment by bendrucker** [comment]
Don't mutate your modules in your tests. Instead re-proxyquire with the values you want. Otherwise your tests are coupled to each other unnecessarily.
