### ISSUE TITLE
Proxying JSON files

### ISSUE THREAD

**Issue by niksy** [thlorenz/proxyquire#137]
When I try to proxy some JSON file, in every case original file gets required, but when I use `noCallThru` proxied JSON file gets required. Is this intentional and is there a better method for proxyquireing JSON files?

**Comment by bendrucker** [comment]
Example?

**Comment by manojlds** [comment]
Had the same case:

a.js:
```js
var config = require('../config.json');
```

test.js:
```js
var a = proxyquire('a', 
    { '../config.json': require('../testconfig.json')});
```

**Comment by bendrucker** [comment]
Sorry for the delay here. A failing test would be a nice contribution (as a PR) if anyone's looking to pitch in and move this forward.

**Comment by sonicdoe** [comment]
FYI, I can’t reproduce this with proxyquire v2.0.1 (both with and without *callThru*).
