### ISSUE TITLE
Can I mock a method in the file I am proxyquiring?

### ISSUE THREAD

**Issue by terlar** [thlorenz/proxyquire#138]
I didn't find this in the documentation and I haven't found a way to do this, hence the question.

If I have something like this.

`src/main.js`
```js
var bleno = require('bleno');

var condition = true;

function setup() {
  // Run stuff that starts timers and other unwanted stuff.
}

if (condition) {
  setup();
} else {
  process.exit(1);
}
```

`test/main.js`
```js
var proxyquire = require('proxyquire');

var main = proxyquire('../src/main', {
  'bleno': { '@noCallThru': true }
});
```

I want to mock both `bleno` since that is failing on require if no bluetooth devices are available and the setup method inside the proxyquired `main.js` as it starts timers and other things.

How do I do something like providing a mock for `../src/main`:s own methods, e.g. `setup`.

**Comment by bendrucker** [comment]
You can't overwrite internal functions. Proxyquire overrides requires.
