### ISSUE TITLE
Use with babel-plugin-resolver (non-relative import paths)

### ISSUE THREAD

**Issue by Retsam** [thlorenz/proxyquire#142]
I'm attempting to use proxyquire with code that's compiled with babel-plugin-resolver: a plugin that allows for the use of non-relative paths, and struggling to make it work with proxyquire.

Suppose a directory structure of: 

```
foo
|- bar
    |- baz.js
    |- __tests__
        |- bazTest.js
hodor
|- hodor
    |- hodor.js
```

`babel-plugin-resolver` allows `baz.js` to import `hodor.js` as `import hodor from "hodor/hodor/hodor"` instead of `import hodor from "../../hodor/hodor/hodor"`, but it does so by compiling the import as `require("/Absolute/path/to/my/src/hodor/hodor/hodor").default`.

It's pretty obviously not acceptable to write my unit test logic with an absolute path, like:

```
proxyquire("../baz.js", {
     "/Absolute/path/to/my/src/hodor/hodor/hodor": hodorStub
});
```

Is there any way I can deal with this from proxyquire's side?  One solution I could imagine would be using regex for the stub: 

```
proxyquire("../baz.js", {
    "hodor$": hodorStub
})
```

but I don't believe proxyquire has any support for that.  

Any advice?

**Comment by bendrucker** [comment]
The babel plugin is doing static analysis to find your requires. It's possible to do the same for proxyquire. You'd have to write a more elaborate plugin to detect the node where `require('proxyquire')` is assigned to a variable. You'd then have to track function invocations of that variable and look at the object passed in. You could re-map the keys as absolute paths relative to the filename to match the transpilation that babel is doing. This might be a helpful starting point if you want to undertake this:

https://github.com/thlorenz/proxyquireify/blob/master/lib/find-dependencies.js

You could also go with a somewhat dirty solution that leaks knowledge of your intent to rewrite all the `require` paths into your code. You'll have to use the dynamic key name syntax `{[a + b]: c}` to avoid crazy verbosity. You can go through and generate absolute paths relative to your test file.

FWIW, I avoid transpilation and especially path rewriting in Node exactly for this sort of reason. I found that complex compile steps created too many incompatibilities and obscure bugs with other tools. I strive to always write code where `node *` just works.
