### ISSUE TITLE
Possible to check if a class was required?

### ISSUE THREAD

**Issue by gauntface** [thlorenz/proxyquire#143]
Bit of a weird test so bare with me.

I'm writing a helper library for selenium and one thing I'm doing is that when a "LocalBrowser" is requestws, i.e. Chrome, or Firefox, I `require()` the appropriate driver (i.e. `require('chromedriver`) or `require('geckodriver')`).

These driver dependecines are options for the library, so they may be available, they may not be.

So the `require()` call for these modules are wrapped in a try and catch statement. 

What I'd like to do, is use proxyquire to essentially simulate a module that exists and doesn't exist (i.e. `require('exampledriver')`.

This I can do with the following for non-existing module:

    const ProxiedLocalBrowser = proxyquire('../src/local-browser.js', {
      'exampledriver': null,
    });

and for existing module:

    const ProxiedLocalBrowser = proxyquire('../src/local-browser.js', {
      'exampledriver': {
        '@noCallThru': true,
      },
    });

The only thing I can't find a way to do, is check if the module was actually required.

This is useful because modules like `chromedriver` etc will manipulate the `path` to include the driver binary, which the selenium server will then find and use, as soon as they are required in. This means, my code literally *just* needs to require them, the returned module isn't needed.

So, how can I check that `require('exampledriver')` actually occurred? It looks like require.cache doesn't have anything useful and I couldn't find anything similar on the proxyquire module.

Cheers,
Matt

**Comment by bendrucker** [comment]
Proxyquire doesn't expose any functionality for that. You could probably monkey-patch your way to this if you really wanted: https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L140-L168
