### ISSUE TITLE
Question - dealing with require.exports = ClassConstructor

### ISSUE THREAD

**Issue by d1manson** [thlorenz/proxyquire#144]
I originally asked this on [SO](http://stackoverflow.com/q/40677724/2399799) but got no reply - I'm guessing here would be a better bet....

If I have a module that exports a single class, how can I mock/stub it with `proxyquire`?

Currently I have the following, which seems to work, but is rather lengthy and doesn't make proper use of `proxyquire`:

**some-class.js**

    var SomeClass = function(){
      console.log("constructed SomeClass");
    }
    SomeClass.prototype.shout = function(){
      console.log("HELLO!");
    }
    module.exports = SomeClass;

**my-module.js**

    var SomeClass = require('some-class');
    module.exports.doSomething = function(){
      var a = new SomeClass();
      a.shout();
    }

**test-my-module.js**

    // :::: bit I'd like to avoid ::::::
    var cls = require('some-class'); 
    var SomeClassStub = function(){
      cls.apply(this, arguments);
    };
    SomeClassStub.prototype = Object.create(originalCls.prototype);
    // :::::::::::::::::::::::::::::::::

    var myModule = proxyquire('my-module', {
      'some-class': SomeClassStub
    });

    SomeClassStub.prototype.shout = function(){
      console.log("whisper");
    }
    
    myModule.doSomething();

Note that I am fairly new to mocking (and testing!) so I might be missing something obvious, but I was hoping that `proxyquire` would deal with my problem itself (rather than me needing to use another library or write the above code).

Thanks!

**Comment by bendrucker** [comment]
What are you expecting proxyquire to do here for you? Automatically set up a constructor and clone a prototype for you? Because it doesn't do that.

**Comment by bendrucker** [comment]
If you pass in a function as a stub proxyquire will try to extend your stub's prototype with the original:

https://github.com/bendrucker/fill-keys/blob/master/index.js#L10-L12

So if you want to override a class, you have to override the constructor (always) but can provide only the method you intend to override on your stub's prototype. Does that help?

**Comment by d1manson** [comment]
Hmm, I think that's the answer I was looking for.  Thanks!
It would be nice though if `proxyquire` provided the original constructor to the stubbed function so that it can use `apply` (or whatever) as needed...actually, maybe it is already available as `this.prototype.constructor`? 
If I can do what I wanted here, I suggest putting an example in the docs, because I stared at them for a while but couldn't see what I should be doing.

Thanks for the quick replies.

**Comment by bendrucker** [comment]
No problem. I agree that class examples would be helpful. Will keep it in mind for future work.

**Comment by montrealist** [comment]
Hey @d1manson did you ever figure out how to optimize this with proxyquire? Grappling with the same issue now.

**Comment by kenkopelson** [comment]
Hey Ben, thanks for all your great work on proxyquire!  Just one question if I may.  I'm asking proxyquire to stub some methods in a mongoose model.  When the model gets loaded in the underlying module (Node), proxyquire is turning it into an object, and removing it's javascript class nature (constructor).  This means I can no longer call "new" on the model object to create a new instance of the model.  I was hoping it would just load the Model class/constructor in like normal, and then replace the methods I give it to replace.  By rendering the Model class as a javascript object, it basically breaks the code.  Can anything be done?

**Comment by bendrucker** [comment]
Use `noCallThru` and provide a full mock if class semantics are important
