### ISSUE TITLE
Stubbing modules deeper in hierarchy does not work (or I'm doing something wrong)

### ISSUE THREAD

**Issue by tomitrescak** [thlorenz/proxyquire#146]
Hi, thanks for the great module! It is the best thing that happened to me in combination with wallaby.js ;) I have a problem with stubbing modules, that are not directly in required files. 

I have file A:

```
import { value } from 'foo';
export var A = foo.value;
```

file B

```
import { A } from './A'
export var B = A;
```

file C

```
import { B } from './B'
export var C = B;
```

Now, in my test if I use proxyquire

```
const c = proxyquire('./C', { foo: { value: 2} } )
```

The foo is still loaded. I can see that proxyquire is still tryiong ot load the original foo, and not use the stubbed one. How can I prevent that?

**Comment by bendrucker** [comment]
`noCallThru`

**Comment by tomitrescak** [comment]
I tried that even before, but no luck.

**Comment by kimmobrunfeldt** [comment]
This type of proxyquire usage doesn't work for me either. I needed to add `'@global': true` to make it work.
