### ISSUE TITLE
Question: can I proxyquire a dependency of a parent class?

### ISSUE THREAD

**Issue by jccpdev** [thlorenz/proxyquire#151]
I have a situation where I want to stub a required module of a parent class, is this possible?

**Comment by bendrucker** [comment]
Happy to help if you provide some code as an example

**Comment by jccpdev** [comment]
Hello @bendrucker, I actually had one of the guys at me company show me how. I am just going to close this.

Thank you anyways.
by the awesome module, I use it every day!
