### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by dylanparry** [thlorenz/proxyquire#152]
Hi,

I'm having an issue where regardless of what module I 'require', I'm getting the error `TypeError: Cannot read property 'bind' of undefined`

![error](https://cloud.githubusercontent.com/assets/3692873/22025237/ce7acbd4-dcc4-11e6-8419-f1348fbbb7d1.png)

In this example, I'm loading in a module that uses a couple of React components, and as I don't want the entire app to be mounted, I'm attempting to mock the components that it would normally load.

If I do a straight `import Bootstrap from '../src/bootstrap'`, then I get no errors and my tests run just fine (although everything takes longer as it's loading in a full app, so it's not that the module doesn't exist or anything like that.

Any idea why this might be happening?

**Comment by bendrucker** [comment]
Would be helpful to get an example I can run in Node, ideally without the use of import.

**Comment by dylanparry** [comment]
test.spec.js:

```javascript
const proxyquire = require('proxyquire');

// Stub out the components used by the Bootstrap class
const test = proxyquire('./test', {
  './components/app': { default: () => true },
});

console.log(test.app.default()); // Should output "true"
```

test.js:

```javascript
const app = require('./app');

module.exports = {
  app: app,
};
```

The `./components/app` file shouldn't need to exist as I'm attempting to mock it via proxyquire, is that a correct assumption?

![error](https://cloud.githubusercontent.com/assets/3692873/22030456/8d76359a-dcd5-11e6-9f13-9db4ba009d7f.png)

This is what I'm getting when running the test file through Jest. I've omitted any actual tests from the file, as they're just noise that has no bearing on the problem.

It appears from the error that the file I'm testing (ie. `test.js`) isn't found, so when I attempt to mock the `./components/app` file, it says that it can't bind to undefined.

If I remove the second parameter to `proxyquire`, I get `proxyquireError` as a message instead.

**Comment by dylanparry** [comment]
Just a thought, as some of the files in my project have the `.jsx` extension, could it be this that's causing it? So it fails to find the modules because they don't have a `.js` extension? If so, is there a setting I can change to make this work?

**Comment by bendrucker** [comment]
Can you upload this all as a project so I can npm install and npm test to reproduce the issue?

**Comment by dylanparry** [comment]
Hi. I've realised that I'm attempting to do something that probably shouldn't work, due to the set-up of my project, so have decided to try a different approach. I'll close this bug now—thanks.

**Comment by karlhorky** [comment]
Ran into this today, and it turned out to be because of Jest (Jest is incompatible): https://github.com/facebook/jest/issues/1937#issuecomment-254089972

**Comment by dylanparry** [comment]
I came to a similar conclusion when I remembered that Jest has its own mocking abilities :)
