### ISSUE TITLE
Fake module presence

### ISSUE THREAD

**Issue by iatsiuk** [thlorenz/proxyquire#153]
How to simulate that some module is installed?

Content of `index.js`:
```js
module.exports = () => {
  try {
    require('not-present');
  } catch (err) {
    console.error('not found');
  }
}
```
Content of `test.js`:
```js
const proxyquire = require('proxyquire');
const test = proxyquire('./index.js', {
  'not-present': () => console.log('ok'),
});

test();
```

```sh
$ node test.js 
not found
```

**Comment by bendrucker** [comment]
Your example is correct. You'll need to enable `noCallThru` though. It's called out/explained in the docs here:

https://github.com/thlorenz/proxyquire#preventing-call-thru-to-original-dependency

**Comment by vikikamath** [comment]
Not sure why the following did **not** work 
```js
// test.js

const test = proxyquire('./index.js', {
  'not-present': () => console.log('ok'),
  '@noCallThru':  true
});
```
But the following worked:
```js
// test.js

const test = proxyquire.noCallThru()(('./index.js', {
  'not-present': () => console.log('ok')
});
```
Any idea?

**Comment by bendrucker** [comment]
@vikikamath 

https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L179

`@noCallThru` is a property of the **stub**, not the object of stubs. 

`
{nonexistent: Object.assign(() => console.log('ok'), {'@noCallThru': true})}
