### ISSUE TITLE
How to handle daisy changed function calls and the use of spread...

### ISSUE THREAD

**Issue by webbbret** [thlorenz/proxyquire#154]
I have the following function:

```
function buildAWidget(graphId) {
    var aDeferred = someClass.defer();
    var query = someMagicaQuery(graphId);
    someOtherRequiredClass.someMethod(query, blah, blah)
        .then(function funcA(data) {
            return data;   
        })
        .spread(function funcB(data, moreData) {
            return funcC(data, moreData);
        })
        .then(function funcD(data) {
            aDeferred .resolve(data);
        })
        .catch(function rejectRoutine(error) {
            aDeferred .reject(error);
        })
        .done();

    return aDeferred .promise;
}
```

For my test, a few things occur:

1. It fails on spread stating that the .then(..).spread is not a function. So I am not sure I could even mock that function since it belongs to JavaScript, or I believe es5?
2. Some of the functions being called within the chained then never get called because they are functions that are not part of the export statement, and seem to only be referenced by the method that is part of the exports = module.exports

Can you please point me to an example that deals with this type of thing? Is it possible to stub these daisy chained functions in my test? 

Many thanks in advance.

**Comment by bendrucker** [comment]
Hi, I read through this twice and can't make sense of what you're trying to do. Since this isn't a bug/request I'm going to go ahead and close this out. If you're willing to create a repo with a sample project I can `git clone && npm install && npm test` to see a failure I'd be happy to try to help then.
