### ISSUE TITLE
Nested modules are not mocked

### ISSUE THREAD

**Issue by bisubus** [thlorenz/proxyquire#157]
Here is a hierarchy of modules I'm using. 

I would expect that `abc/c/index.js` will be mocked, because `./c` path is relative to `abc/a.js` and `abc/b.js`. If `require('./c')` happens in `abc/b.js`, it is not mocked. But if `require('./c')` is in `abc/a.js`, it is mocked.

I've honestly RTMed, but the purpose of `noCallThru` here is not clear for me also. I would expect that it will prevent unmocked modules from being called and possibly provide me with details on which paths were not mocked, but it just... calls through.

_index.js_
```js
const proxyquire = require('proxyquire').noCallThru();

const a = proxyquire('./abc/a', {
  './c': 'c mocked',
});
console.log(a);
```

_abc/a.js_
```js
const b = require('./b');
// ...
module.exports = b;
```

_abc/b.js_
```js
const c = require('./c');
// ...
module.exports = c;
```

_abc/c/index.js_
```js
// ...
module.exports = ['c'];
```

Windows, Node 7.2.0
proxyquire 1.7.11

Possibly related to #146.

**Comment by bendrucker** [comment]
https://github.com/thlorenz/proxyquire#globally-override-require

This is specifically called out as not recommended since globally mocking dependencies means your tests are no longer isolated and you're leaking knowledge of n > 2 degree dependencies of the module under test.

**Comment by bisubus** [comment]
@bendrucker Thanks, indeed, this worked for me:
```
'./c': Object.assign(['c mocked'], { '@global': true })
```

But this also means that modules need `@global` property and cannot be primitives, right? This is something that troubled me in `rewire`.

**Comment by bendrucker** [comment]
Correct, strings and numbers won't work. Functions and anything else that allows property assignment will. The real answer here is don't do global mocking. It makes sense when you have a global dependency system (e.g. injector a la C#). `require` is isolated and relative to the source module and your tests should be too.
