### ISSUE TITLE
if the module is not yet in require cache (.noPreserveCache() NOT being used) proxyquire will install the proxied module in require cache

### ISSUE THREAD

**Issue by is24i18n** [thlorenz/proxyquire#158]
// a.js
exports.foo = function () {require('./b').foo()}
// b.js
exports.foo = function () {console.log('foo');}

// test1.js, prints bar, bar (unexpected)
require('proxyquire')('./a', {'./b': {foo: function () {console.log('bar');}}}).foo();
require('./a').foo();

// test2.js, prints bar, foo (expected)
require('./a');
require('proxyquire')('./a', {'./b': {foo: function () {console.log('bar');}}}).foo();
require('./a').foo();

**Comment by bendrucker** [comment]
That's expected, proxyquire uses the normal require cache by default

**Comment by is24i18n** [comment]
IMHO if the module is not in require cache proxyquire should

option 1) install the original, not yet proxified module in the cache 1st, so that later calls to require can get the unmodified version
option 2) leave the cache empty, so that later calls to require can install the original version

but again this seems to be a feature..
