### ISSUE TITLE
Using proxyquire with requires with arguments

### ISSUE THREAD

**Issue by fetherolfjd** [thlorenz/proxyquire#159]
Our application uses express and adds routes in the following style:

    // app.js
    var express = require('express');
    ...
    var app = express();
    app.use(...);
    ...
    require('./routes/fileRoutes')(app);
    ...
    module.exports = app;

    //fileRoutes.js
    module.exports = function (app) {
      var router = express.Router();
      app.use('/service/files', router);
      var methodIWantToStub = function() {
        ...
      };
      router.post(...);
      router.get(...);
    };

In our test file we are just requiring app.js and making the calls to the API with supertest like this:

    // testFileRoutesWebAPI.js
    var request = require('supertest');
    describe('test', function() {
      var app = require('../app');
      it('should do stuff', function(done) {
        request(app)
          .get(...)
         .....
      });
    };

Now, I'd like to use proxyquire in the test to stub out `methodIWantToStub` in fileRoutes.js, but can't quite get the syntax, and my Googling is failing me. Is it even possible with proxyquire with the `require('./routes/fileRoutes')(app)` that we use in app.js?

Thanks for any help you can provide.

**Comment by bendrucker** [comment]
Sure! You need to replace your actual module with a function that takes in an `app` and do what you want. You cannot override `methodIWantToStub` since that's local to your source code. Proxyquire allows you to replace dependencies before a module is loaded, not change the runtime behavior of your code.
