### ISSUE TITLE
Proxyquire not working as expected with cloudinary

### ISSUE THREAD

**Issue by raghavgujjar** [thlorenz/proxyquire#160]
I'm trying to stub cloudinary so that it doesn't call a real service in the unit tests. This is the test in the unit test folder of my express app. I'm using super test. The route /upload is using a method in the folder services/uploader of the application which depends on cloudinary. The way to invoke is cloudinary.uploader.upload(input, callback) and needs a config before this, clooudinary.config. It ends up calling the actual method every time even though I've closely followed the documentation provided in README.md.
```
 var uploader = proxyquire('../../services/uploader', {
            'cloudinary': {
                'uploader': {
                    upload: function (input, callback) {
                        console.log('came here 2');
                        callback({});
                    },
                '@global': true
                },
                'config': function (config) {
                    console.log('came here: ' + JSON.stringify(config));
                }
            }
        });
        request(app)
        .post('/upload')
        .set('Content-Type', 'application/json')
        .send(JSON.stringify({file: fileData}))
        .expect(200)
        .end(function(err, res) {
            assert.equal(res.body.info, 'Upload complete', 'File upload complete');
            done();
        });
    });
```
I'm on windows machine

**Comment by raghavgujjar** [comment]
I'm spending a lot of time @thlorenz . Any immediately assistance will be highly appreciated.

**Comment by bendrucker** [comment]
Hey man, please don't come into an open source project demanding immediate assistance. Because you didn't supply the source code it's impossible to know what mistake you made. If you supply the source module I can try to help.

**Comment by raghavgujjar** [comment]
@bendrucker First of all thanks for misconstruing the issue I have posted. I didn't demand immediate assistance. I just said "Any immediate assistance will be appreciated". I'm actually OK to spend some more time debugging the issue myself. I just though I could reach out to save me some time. This is the source code module: https://github.com/cloudinary/cloudinary_npm

**Comment by bendrucker** [comment]
Sorry to come off a bit aggressive but pinging the author of a module and pushing for special time sensitive help for your own project is not cool. You might consider that Thorsten has 350 other modules to maintain and a full time job. Sarcastic responses aren't helpful to anyone either. 

The module you linked to is not your source code. We need to see _your_ source code, not the module you're consuming.

**Comment by raghavgujjar** [comment]
Sorry. I didn't mean to be sarcastic. The code is in a private repository.
I'll try to summarize. It is an express app.
test/routes/upload.js
```
var proxyquire = require('proxyquire').noCallThru();
var request = require('supertest');
var app = require('../../app');

 var uploader = proxyquire('../../services/uploader', {
            'cloudinary': {
                'uploader': {
                    upload: function (input, callback) {
                        console.log('came here 2');
                        callback({});
                    },
                '@global': true
                },
                'config': function (config) {
                    console.log('came here: ' + JSON.stringify(config));
                }
            }
        });
        request(app)
        .post('/upload')
        .set('Content-Type', 'application/json')
        .send(JSON.stringify({file: fileData}))
        .expect(200)
        .end(function(err, res) {
            assert.equal(res.body.info, 'Upload complete', 'File upload complete');
            done();
        });
    });
```

app.js
```
var express = require('express');
var app = express();
var upload = require('./routes/upload');
app.use('/upload', upload);
module.exports = app;
```

routes/upload.js
```
var express = require('express');
var router = express.router();
var uploader = require('../services/uploader');

router.post('/upload', function(req, res, next) {
         uploader.upload(input, function(result) {
                 res.json(result);
      });
});

module.exports = router;
```
services/uploader.js
```
var cloudinary = require('cloudinary');
cloudinary.config({});

module.exports = {
     upload: function(input, callback) {
           cloudinary.uploader.upload(input, function(result) {
                   callback(result);
          });
    }
}
``

**Comment by bendrucker** [comment]
Cool, this is exactly what I need to help. Pretty sure the reason this is broken is because you require the app first. Proxyquire isn't really a mocking library the way sinon is where you patch global state. Ideally you keep your mocking isolated to a specific copy of the module via require and a lot of complex machinery inside proxyquire/`Module`. 

You're basically getting your whole app initialized and then calling `proxyquire` which in effect does nothing. You've already loaded up all the modules. 

Best idea is to not use `@global` as the docs advise. Require the routes/upload module directly and test it in isolation. You're passing your services/cloudinary module to proxyquire even though it's not the module under test. You want to test the routes module while mocking the services module and then also test the services module while mocking the cloudinary module.

**Comment by raghavgujjar** [comment]
@bendrucker thank you for your suggestions and being on top of this one replying immediately.
