### ISSUE TITLE
Support for wildcard strings

### ISSUE THREAD

**Issue by Floriferous** [thlorenz/proxyquire#171]
I have a use case where it would be helpful if I could stub modules using wildcard strings.

As an example, one of my own files isn't required during testing, and messes with my tests. But it is imported using various paths:
```js
import bar from '../myModule'
```
or
```js
import bar from '../../myModule'
```

I wish it was possible to stub it out this way:

```js
proxyquire('./foo', { '*myModule': {} })
```

Is there another way I can do this now, or could this feature be added?

**Comment by bendrucker** [comment]
No way do to this. I doubt we'd ever include something like this, adding new module resolution outside of explicit/exact matching is against the spirit of proxyquire.

**Comment by rostislav-simonik-plc** [comment]
github.com/ariporad/pirates
