### ISSUE TITLE
proxyquire does not like import

### ISSUE THREAD

**Issue by jacopolanzoni** [thlorenz/proxyquire#172]
I have the following module in a file constants.ts:

`import * as _ from 'lodash';`
`config = require('/config.json');`
`export namespace constants {`
`  export const myVariable = config.myField;`
`}`

Here, lodash is used for some manipulation in lines that I have removed to provide a minimal code. I am trying to write a test as the following:

`import { expect } from 'chai';`
`describe('Constants', function () {`
`  const proxyquire = require('proxyquire');`
`  it('should set the constants from /config.json', function () {`
`    const constants = proxyquire('./constants.ts', { '/etc/vcc/config.json': {`
`      myField: 'myValue'`
`    } });`
`    expect(constants.myVariable).to.equal('myValue');`
`  });`
`});`

Yet, I get the following error:

`constants.ts:13`
`import * as _ from 'lodash';`
`^^^^^^`
`SyntaxError: Unexpected token import`

Can you please let me know if I am importing/using proxyquire in the wrong way?

**Comment by bendrucker** [comment]
It's not exactly the same situation, but this is the best answer I can offer: https://github.com/thlorenz/proxyquire/issues/169#issuecomment-312449177

Proxyquire is a node module and it's up to you to figure out how to make things work with any "fake" module system you choose to use on top of Node/`require`/CommonJS. I've personally never used Typescript so I couldn't even tell you where to start here.

**Comment by bendrucker** [comment]
Another way to phrase this: `proxyquire` is just using the internals that back `require` to load the module you tell it. If your module isn't valid JS (like `import`) Node will bail.

**Comment by npHavens** [comment]
Hi, I love this library and I'm forced to use use typescript for work. Has anyone found a workaround for this or know a similar library for TS?  I am not asking to re-open the issue.  Just a fan of the library and I need to write express routing tests.

**Comment by bendrucker** [comment]
Take a look at the transpiled output from Typescript. Assuming it’s like Babel and you’re ultimately still compiling down to good old requires you can figure out what’s going on.
