### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by ip** [thlorenz/proxyquire#177]

**Comment by mariojunior** [comment]
I just came here to check the same.
I've used proxyquire for one year or more, but when I typed 'proxyqu...' my Editor (Vscode) suggested proxyquire and proxyquire-2 ... then I'm checking what are the differences. 

Proxyquire-2 is a fork of this one (which is original) and introduced some new methods, but, to be honest, are useless to me ... although, I'm going to use proxiquire-2 once the forked part continues the same.

**Comment by bendrucker** [comment]
Sure! Shame someone chose to fork and throw a 2 on at the expense of confusion. We’re fixing bugs as they come and responding to questions. Thorsten and I both maintain quite a lot and don’t always have time to chase down everything. I use proxyquire in tons of projects and effectively consider it “done.” Nothing’s truly done but pq is stable with tons of happy users.

**Comment by ip** [comment]
It's good to know that it's stable. It was just suspicious to me that the last commit was half a year ago.

**Comment by mariojunior** [comment]
Guess what... since the 'new-and-not-documented' methods from proxyquire-2 are useless to me, I'm holding the original proxyquire on my project. :)

**Comment by bendrucker** [comment]
I usually look at open issues/PRs as a signal of project health. If there are lots of serious gaps that aren't being addressed that's a problem. Some projects are just "done," never literally, but in the sense that they're stable, tested, and the authors are committed to a small API.
