### ISSUE TITLE
Stubbing with the es6 class instances

### ISSUE THREAD

**Issue by CMCDragonkai** [thlorenz/proxyquire#178]
I noticed that if you stub with an instance of an ES6 class for a given object it often doesn't work because the class methods are in the prototype of the instance, and not directly on the instance. Is there a way to make require work on the prototype functions as well?

**Comment by bendrucker** [comment]
Hi, can you please share an example of what you're trying to do? See [fill-keys](https://github.com/bendrucker/fill-keys) for the strategy pq is using to copy.

**Comment by kub1x** [comment]
Think I might have the same issue. I want to mock redis library using the [redis-mock](https://github.com/yeahoffline/redis-mock). Since redis-mock [exports an object instance](https://github.com/yeahoffline/redis-mock/blob/master/lib/redis-mock.js#L101), I had to get the `__proto__` out from it and pass it to proxyquire. 

    const redisMock = require('redis-mock');
    const app = proxyquire('../app/app', {
      'redis': redisMock.__proto__,
    });

**Comment by kub1x** [comment]
@bendrucker Yep. fill-keys uses merge-descriptors, which [checks hasOwnPropperty](https://github.com/component/merge-descriptors/blob/master/index.js#L49). You might be better of using something like: 
    for (prop in mock) {
        targetLib[prop] = mock[prop]; 
    }
and you'd drop a trivial dependency as a bonus.

**Comment by bendrucker** [comment]
It's never that easy, copying the descriptors was a past feature/bug request. Happy to consider alternate behavior but we are trading bugs and doing simple assignment in a loop.

**Comment by kub1x** [comment]
@bendrucker Cool. I tried changing it in the proxyquire and it somehow worked for me but didn't pass the tests. I understand there is much more cases to consider. The `__proto__` workaround did the job for now.

**Comment by bendrucker** [comment]
Cool, glad you have something for now. There are two fundamental issues open: this and module caching. I'm interested in looking at some point but haven't reserved time for it yet.

**Comment by JimTheMan** [comment]
calling .proto on your classes to mock instance functions is super ugly. @bendrucker is this really the correct api?
