### ISSUE TITLE
Proxying nested properties of destructed assignments

### ISSUE THREAD

**Issue by rbriank** [thlorenz/proxyquire#180]
#156  works for top-level properties but not for proxying nested properties.  For example:

**config.js**
```
module.exports = {
  top: {
    middle: 123123,
    inner: 'abcabc'
  }
}
```

**app.js**
```
...
const { top: { middle, inner } } = require('config')
...
```

**app.test.js**
```
...
const app = proxyquire('./app', {
  './config': {
    top: () => { return {
      middle: () => 8098098,
      inner: () => 'qwertqwert'
    }}
  }
})
...
```

Results in `middle` and `inner` being assigned the values from `config` instead of being proxied.

I tried making `top` an object instead of a function returning an object but that made no difference.

**Comment by bendrucker** [comment]
In your test `top` is a function and in your source it's an object, could that be it?

**Comment by rbriank** [comment]
No - that was the solution put forward in #156 for dealing with destructuring assignment.  It works but only for top-level, not for nested attributes.

I have tried making it an object, as well as making the properties inside objects and other permutations but nothings has made a difference.

**Comment by bendrucker** [comment]
Can you submit a failing test in a PR for this? My understanding was that destructuring was just syntactic sugar so this doesn't make sense.

**Comment by rbriank** [comment]
It is very strange. Even the answer to #156 doesn't entirely make sense to me.

**Comment by rbriank** [comment]
Here is the PR: https://github.com/thlorenz/proxyquire/pull/182

It works though, so now I have to figure what is going with my code!
