### ISSUE TITLE
Prevent module initialization code from executing

### ISSUE THREAD

**Issue by froxCZ** [thlorenz/proxyquire#181]
I do not want any connection to database or redis during my tests, but at the same time, I want to have the connections initialized when the application starts.

Let's have the following files
```
// db.js
import pgPromise from 'pg-promise'
const db = pgPromise(config.postgres.url)

export function getUsers(){
  return db.query('SELECT * from users)
}


// service.js
import * as db from './db`
export function getUsers(){
  return db.getUsers()
}

```

I can use proxyquire to mock `db.js#getUsers`, but I can't prevent the test from initializing connection to database, because the initialization code in `db.js` is always executed.

Is there a way how to prevent `const db = pgPromise(config.postgres.url)` from executing with proxyquire or something else? Thanks!

**Comment by bendrucker** [comment]
Hi, The idea of "preventing module initialization" isn't sound—a module is either loaded or not. Using import/export syntax muddies things a bit, but code is code, whether it's a function call or declaration. You can certainly replace `pgPromise` with a mock using proxyquire.
