### ISSUE TITLE
Confused on which name to match based on `path` example in README

### ISSUE THREAD

**Issue by thisismydesign** [thlorenz/proxyquire#183]
Hey,

I found the following line in the readme confusing:

`var path = require('path');`

Because I wasn't sure if later I need match the name of the variable or the argument of require. While naming them the same is common for simple examples this might not always be the case (e.g. dependencies whose name includes a dash).

Could you clarify this in the README?

**Comment by bendrucker** [comment]
Hey, I think the inclusion of `simple-get` and the API docs section explain this properly. If you can think of a concise way to convey that earlier in the usage examples I'd be happy to review a PR.
