### ISSUE TITLE
Override dependency with a plain object

### ISSUE THREAD

**Issue by thisismydesign** [thlorenz/proxyquire#184]
Hey,

The README does a nice job detailing how you can override methods of dependencies. My use case  however was this: `Object.keys(dependency)`. So I simply wanted to override the dependency with an object.

Turns out this is possible using `noCallThru()` (or at least it has the desired side effect) but it took some time to figure this out.

Could you mention it in the README?

**Comment by bendrucker** [comment]
Hey, please submit a PR! That's a good point and might not be obvious to a new user, we'd welcome your contribution.
