### ISSUE TITLE
Proxyquire cache affects node's cache

### ISSUE THREAD

**Issue by RiddleMan** [thlorenz/proxyquire#186]
Issue is pretty simple to reproduce what I'd like to do it below

./bar.js
```javascript
module.exports = 'bar';
```

./foo.js
```javascript
const bar = require('./bar');

module.exports = bar;
```

./foo.test.js
```javascript
const proxyquire = require('proxyquire').noCallThru();
const fooMock = proxyquire('./foo', {
    './bar': 'fakeBar'
});
const fooReal = require('./foo');

console.log('MOCK foo');
console.log(fooMock);
console.log('REAL foo');
console.log(fooReal);
```

When you run `node ./foo.test.js` it will print following text in console.
```
MOCK foo
fakeBar
REAL foo
fakeBar
```
I would expect `REAL foo` to be just `bar` instead of `fakeBar`.

It's even getting worse when you are running big set of unit test, because in the most of cases we can't reason about things which we are testing.

Thank you in advance for that fix!

**Comment by bendrucker** [comment]
Hey, I agree this is how it should work. I may have some time to take a deeper look at caching behavior soon (few weeks). It's definitely the biggest source of confusion and complexity in pq.

**Comment by jwalton** [comment]
Failing test case: https://github.com/jwalton/proxyquire/blob/master/test/proxyquire-cache.js#L21-L27

**Comment by jwalton** [comment]
noPreserveCache() fixes this, too (which is weird - this option works the opposite of how I expected it to.  :P)
