### ISSUE TITLE
Can you proxyquire a dependency which is not directly imported with require('...') ?

### ISSUE THREAD

**Issue by asskopos** [thlorenz/proxyquire#187]
Hi guys,

I am wondering if there is a way to proxyquire a dependency which is not directly imported with the require statement. E.g. I am using sequelize and have exported the sequelize model as explained in the go-to-guide http://sequelize.readthedocs.io/en/1.7.0/articles/express/#modelsindexjs .

My problem is, that I am requiring a model like so:

```
var models = require('path/to/models/index');
var User = models.user;
```

Now I want to overwrite the User with a mocked model in an integration test and thus wanted to write something like:
```
var proxyquire = require('proxyquire');
var SequelizeMock = require('sequelize-mock');
var dbMock = new SequelizeMock();

var UserMock = dbMock.define('user', {
  name: 'MockTest'
});

var abstractUserHandlerMock = proxyquire('../../../lib/trigger/handling/abstractUserHandler', { '../../../models/user': UserMock});
```

But since I am importing the user model in the abstractUserHandler module with the statement `var User = models.user` instead of a require-statement (e.g. `var User = require('path/to/my/models/user');`) which I could overwrite with proxyquire, I don't see a way how to handle this. Without stubbing the whole sequelize instance which is a great overhead for my tests.

Can you provide some information for  this? Is this possible? Doing the export of sequelize in another way in order to load the dependencies like `require('User');` should not be considered as an alternative afaik.

Best regards

**Comment by asskopos** [comment]
I have found it by myself. 10 minutes coffee break can help a lot of the brain is stucked. :D 

```
var UserMock = dbMock.define('user', {
  name: 'MockTest'
});

var abstractUserHandlerMock = proxyquire('../../../lib/trigger/handling/abstractUserHandler', { '../../../models':
  {user: UserMock}
});
```

**Comment by bendrucker** [comment]
Hi, this seems pretty specific to your setup and not generalizable. If you think there's a contribution to be made here please feel free to send a PR.
