### ISSUE TITLE
Error when running with wallaby.js on Node

### ISSUE THREAD

**Issue by alexmbrown** [thlorenz/proxyquire#195]
I'm receiving the following error when I attempt to require another file `TypeError: Cannot read property 'split' of undefined` from the line invoking the proxyquire method when running my tests using wallabyjs. I do not receive this error when I use the jasmine test runner. Here is an example of when the error occurs

example.js:
```
const foo = require('../foo')

module.exports = function getFoo() {
  return 'hello ' + foo();
}
```

example.spec.js:
```
const proxyquire = require('proxyquire')

describe('Example', () => {
  let fooBar
  let foo

  beforeEach(() => {
    foo = {
      bar: 'mock bar'
    }

    fooBar = proxyquire('./example.js', {
      '../foo': () => 'world'
    })
  })
    
  it('should log "hello world"', () => {
    console.log(fooBar.getFoo())
  })
})
```

**Comment by bendrucker** [comment]
Hi, we can help you with your setup but I don’t expect this is an issue with proxyquire. If you’d like me to take a look please share a link to a repo where I can clone, npm install, and npm test. I should also be able to pass the inspect flag to npm test to debug and see stack traces for errors.
