### ISSUE TITLE
Unexpected issue with extending ES6 class and mocking

### ISSUE THREAD

**Issue by codeburke** [thlorenz/proxyquire#196]
I'm running into an unexpected problem with using proxyquire to mock a Base ES6 class that is extended by a Child class. My use case is more complicated, but I was able to create a fairly simple re-creation here: https://github.com/codeburke/proxyquire-extends-test 
Running `npm install && npm run problem` will execute both the normal Child class and then a Child class with Base swapped for MockBase.

The setup is:
Base exposes a `inc()` method that is overrode in Child and then called again by calling `super.inc()`. 

**./base.js**
```
class BaseClass {
    constructor() {
        this.count = 0;
    }
    inc() {
        console.log('calls base inc');
        this.count += 1;
        return this.count;
    }
}

module.exports = BaseClass;
```

**./child.js**
```
const Base = require('./base');

class Child extends Base {
    constructor() {
        super();
    }
    inc() {
        console.log('calls child inc');
        return super.inc() + 1;
    }
}

module.exports = Child;
```

**../test/mocks/base.js**
```
class MockBaseClass {
    constructor() {
        const self = this; 
        this._incReturn = 0;
        this.inc = () => {
            console.log('calls mock inc');
            return self._incReturn;
        };
    }
}

module.exports = MockBaseClass;
```

**Here is my very simple runner:**
```
const expect = require('chai').expect;
const proxyquire = require('proxyquire').noCallThru();

const MockedChild = proxyquire('./child', {
    './base': require('../test/mocks/base')
});
const Child = require('./child');

// First run the non-mocked child.
// Expected console outpt:
//   calls child inc
//   calls base inc
console.log("Non-mocked output:");
const childInstance = new Child();
expect(childInstance.inc()).to.equal(2);  // passes


console.log("");

// Run the mocked child.
// Expected console outpt:
//   calls child inc
//   calls mocked inc
console.log("mocked output:");
const childMockedInstance = new MockedChild();
childMockedInstance._incReturn = 4;
expect(childMockedInstance.inc()).to.equal(5);  // fails because childMockedInstance.inc() returns 4
```

The first test passes just fine and the console output is as expected.
The second test that uses proxyquire to swap out Base for `../test/mocks/base` fails for 2 reasons:
1. It never executes the Child `inc()` and so I don't see the `calls child inc` console log
2. Since it doesn't execute Child `inc()` it doesn't add 1 and so it just returns 4 instead of 5 causing the `expect` to fail.

I feel like this is user error in some way. Any help in pointing out what I'm doing wrong would be appreciated.

**Comment by bendrucker** [comment]
Hi, sorry for the late response. I just read through this and as far as I see it your test output is expected. Your `MockBaseClass` when constructed sets `this.inc` to a function, overriding the prototype chain. You'd have to set `MockBaseClass.prototype.inc` but you would still initialize `_incReturn` to 0 in the constructor.

Hope that helps! This is generally applicable to JS inheritance, even without involving proxyquire.
