### ISSUE TITLE
Default stub for submodules

### ISSUE THREAD

**Issue by lewispham** [thlorenz/proxyquire#197]
I'm now having troubles with setting default stub for all child modules within the mocked module. For example, if a module contains 10 submodules but I just want to really require 1 particular one for testing some specific methods, and ignore all other modules by returning empty objects. In order to achieve this, for now I'll have to do something like:
```javascript
// a.js
const a1 = require('a1');
const a2 = require('a2');
...
const a10 = require('a10'); 

module.exports = new class {
   method1 () {
    a10.method1();
  }
};

// test-a.js
const a = proxyquire('path/to/a.js', {
  'a1': {},
  'a2': {},
  ...
  'a10': class {
    method1(){
      return someFakeValues;
    }
    method2(){}  
  }
});
describe('Testing method a.method1', () => {
  it('should blah blah', () => {
    assert.equal(a.method1(), expectedValue);
  });
});
```
So I think i'll be more convenience if we can set default stubs for submodules to avoid specifying them one by one.

**Comment by bendrucker** [comment]
Hey, had some trouble following this. Based on my reading I don't think this is something we're going to consider. Proxyquire already passes through for anything you don't stub and will even fill in keys from the source module when you need to do something like just override `fs.readFile`. 

The example seems contrived and not generalizable. There's really no reason why returning an empty object or any value across all modules should be valid. It leads to confusing and brittle code. 

It may fit with the decisions you've made in your application but that's not the test of a good feature.
