### ISSUE TITLE
Doesn't work as expected with 'config' library

### ISSUE THREAD

**Issue by croraf** [thlorenz/proxyquire#198]
I want to mock config 'library' (https://github.com/lorenwest/node-config).

In my tested module I require it at the beginning of the file with:
`const config = require('config');`

In my mocha unit test I mock it with:

```
it('creates ctcApi object assigning it to local variable', async () => {
  const exampleConfig = {
    abc: {
	version: 3,
	host: 'localhost'
     }
  };

  const ctcApiLibUtil = proxyquire('../../../a/apiLibUtil', {
	'config': exampleConfig
  });

  console.log(exampleConfig);
});	
```

**But what is logged is not the mocked `exampleConfig`, but the real configuration object from configuration file.** Why, and how to fix it?

P.S. On `const config = require('config');` the config library loads the configuration file and makes config object available using the `config` variable.

**Comment by bendrucker** [comment]
From what I can tell from a brief peek at that module you're not using it properly. It has `get` and `set` methods among other things.

We need a fully reproducible example to offer support for your particular setup.

You should also read the docs for `noCallThru`.

**Comment by croraf** [comment]
`config.get(propertyName)` and `config.set()` are methods to get the config properties; but they can also be gotten with `config.propertyName` directly.

I assumed that in proxyquire it will just substitute `require('config')` with the provided `exampleConfig` object. But under the hood it also loads config library? 

I assume the config library then modifies the planted `exampleConfig`!?
