### ISSUE TITLE
Cannot proxyquire es6 dependencies

### ISSUE THREAD

**Issue by nishant-jain-94** [thlorenz/proxyquire#202]
Cannot proxyquire es6 modules.

Using MongoConnector in app.js
```
// app.js
import express from 'express';
import graphqlHTTP from 'express-graphql';
import bodyParser from 'body-parser';

import { MongoConnector } from './connectors';
import { schema } from './api';
```

Trying to stub ./connector, but couldn't, throws can't find module.
```
// app.spec.
// Have removed some code for simplicity
beforeAll(async () => {
    const app = proxyquire('../app', {
      './connectors': {},
    });
    await app.listen(config.PORT);
});
```
```
Error: Cannot find module './connectors'.
```

**Comment by bendrucker** [comment]
Is this via babel or using flags for experimental Node features?

**Comment by thlorenz** [comment]
If `./connectors` doesn't actually exist you need to use `noCallThru` option otherwise it'll try to find the original module to fill in the unstubbed properties.

**Comment by bendrucker** [comment]
Once you’re running through Babel we’re not actually talking about es6 modules anymore.

**Comment by bendrucker** [comment]
Closing based on inactivity, this doesn't seem like an ES6 specific issue.

**Comment by arizonatribe** [comment]
Thanks @thlorenz ! After refactoring an NodeJS app to ES6 `import` / `export` syntax the proxyquire functionality no longer worked. Using `noCallThru` fixed it:

```javascript
import pq from "proxyquire"
import sinon from "sinon"
const proxyquire = pq.noCallThru()

const uuidStub = sinon.stub()

const { default: myModule } = proxyquire("/path/to/module", {
  "uuid/v4": uuidStub
})
```
