### ISSUE TITLE
Testing a "dynamically loaded" module

### ISSUE THREAD

**Issue by JohnDMathis** [thlorenz/proxyquire#205]
I have a set of folders that is populated at run-time. Let's call them "dynamic modules":
So I have: `/dynamicModules/someModule.js`

I have static files that may require the dynamic files, like this:
`const someModule = require( "/dynamicModules/someModule" );`

I make sure the dynamic files are loaded long before the code just above is executed. Locally, these dynamic files are loaded manually and are available for stubbing, but in my CI process they are _not_. 

So, a spec file like below fails:
```
const someModuleStub = sinon.stub();
const aModule = proxyquire( "aModule.js", { "/dynamicModules/someModule": someModuleStub } );
```
What I'd like to have happen in this case: proxyquire should simply ignore the fact that the module path doesn't resolve, and give me someModuleStub.

Is there any way to get that sort of behavior? The only alternative I can see is to have dummy files sitting at the location of "/dynamicModules/someModule", which I really don't like.

Thanks!

John

**Comment by bendrucker** [comment]
Yes, that's `noCallThru`:

https://github.com/thlorenz/proxyquire#preventing-call-thru-to-original-dependency

**Comment by JohnDMathis** [comment]
Thanks for the reply @bendrucker. For some reason, I thought @noCallThru was a different scenario.

Perhaps I'm using it incorrectly, but I'm still seeing it complain the path is not valid:
```
const someModuleStub = sinon.stub();
const aModule = proxyquire( "aModule.js", {
  "/dynamicModules/someModule": {
     myFunction: someModuleStub,
    "@noCallThru": true
  }
} );
```
When I run the test:
```
     Error: Cannot find module '/dynamicModules/someModule'
      at Proxyquire._require (node_modules/proxyquire/lib/proxyquire.js:166:19)
```
Am I doing it wrong?

Thanks in advance!

John

**Comment by JohnDMathis** [comment]
Update: I turned off callThru globally, and enabled it only on the modules where it's needed. I like that approach more anyway. Thanks for your help @bendrucker

**Comment by bendrucker** [comment]
In your previous example, `@noCallThru` should be a key on `someModuleStub` as opposed to the whole object of stubs. So `someModuleStub['@noCallThru'] = true`. You can set `proxyquire.noCallThru()` or for a particular stub but not for one invocation.
