### ISSUE TITLE
How can i override a function after 3 files ?

### ISSUE THREAD

**Issue by basilbattikhi** [thlorenz/proxyquire#211]
if the file is not existing in ../repository/demoRepository i mean if this file is requiring another ../repository/demoRepository2 and ../repository/demoRepository2 is Requring another ../repository/demoRepository3 how can i override a function existing in ../repository/demoRepository3 without overriding each path

**Comment by bendrucker** [comment]
Hi, this question is pretty hard to understand, a clearer example would have helped. Based on your comments I think you're looking for [global overrides](https://github.com/thlorenz/proxyquire#globally-override-require).
