### ISSUE TITLE
Proxyquire still calling module after noCallThru()

### ISSUE THREAD

**Issue by maamounapprise** [thlorenz/proxyquire#213]
I am using proxyquire to mock dependency of a module in a class. I used noCallThru() and it still access the original function. 
Example code: 

```
import proxyquire from 'proxyquire'
proxyquire.noCallThru()
class fooFake {
  foomethod () {}
}
const testedModule = proxyquire('../src/tested', {
  '../../fooparent/foo':
    fooFake
}).default
```
orginal foo: 
```
foomethod(){
console.log('it accessed it')
}
```

**Comment by bendrucker** [comment]
Can I please get code I can run? A project I can `git clone && npm install && npm test` works best.

**Comment by maamounapprise** [comment]
It's company's code I can't share it, is it a normal behavior for proxyquire to still access the original module function after being stubbed?  In my case it returns the stubbed result but still access the original module function. 

Another question is if I have module Routes that imports A & B from Alpha as:

` import {A, B} from '../Alpha'
`
inside Routes there is index.js 

index.js
```
import a from './A'
import b from './B'

export const A = a 
export const B =b 
```

how can I mock A & B in one call, I tried doing the following:
const getTestFunc = proxyquire.noPreserveCache().noCallThru().load('../Routes', {
  '../Alpha': MockedA
}, {
  '../Alpha': MockedB
}).getTestFunc

**Comment by bendrucker** [comment]
> It's company's code I can't share it, is it a normal behavior for proxyquire to still access the original module function after being stubbed? In my case it returns the stubbed result but still access the original module function.

Ok, split it out into a project on GitHub and distill it to the bare minimum. I hope you'll understand that I can't help without that.

**Comment by maamounapprise** [comment]
@bendrucker Thanks I realized that it wasn't reaching the modules because all the modules are imported through one class, so I created a mock object that carries all the mock modules and called proxyquire with it and it worked.

**Comment by bendrucker** [comment]
Cool, that's why I always go straight to asking for a full repro! More often than not that's enough to highlight the mistake.
