### ISSUE TITLE
Can not get proxyquire to work with a require that happens in an init function

### ISSUE THREAD

**Issue by intervalia** [thlorenz/proxyquire#215]
I have some code like this:

/lib/mine.js
```
const path = require('path');

function init(cfg) {
  var inner = require(cfg.file);
  inner.doSomething();
}

module.exports = {init};
```

/app.js
```
const mine = require(('./lib/mine');
// Do some stuff here

const cfg = {
  file: '../otherPath/otherFile'
};

mine.init(cfg);
```

The code is much more complicated then this, but this is close enough to show the problem.

I am writing tests for `app.js` above and want to use `proxyquire` for the file `../otherPath/otherFile`

My test file is like this:

app.mocha.js
```
const proxyquire = require('proxyquire').noCallThru();

const ofStub = {
  doSomething: function() {
    // Do something
  }
}

const app = proxyquire('./app', {
  '../otherPath/otherFile': ofStub
});

```

The rest of this file does not matter since the error happens when I try to use `proxyquire` on `app`

I get something like the following error:

`Error: Cannot find module '../otherPath/otherFile`

The thing is that it should not have tried to load that module yet since I have not called `init`

Is there a way to force `proxyquire` to not care if the real module was loaded using `require` when `proxyquire` is initially called and just allow the module to be overridden if and when it is loaded?

**Comment by bendrucker** [comment]
Hey, would you mind creating a simple repro project with this case? I think I understand what you're trying to do here but it'd be a big help to be able to see the error and debug it directly.

**Comment by intervalia** [comment]
The failing code is in a private repo but I will create a public repo that demos the bug.

I will respond to this thread as soon as it is ready but I may not be able to get to it until Monday. 

Thanks!!

**Comment by intervalia** [comment]
OK. Maybe there isn't an error in your code. It looks like my code must be at fault.

Here is the repo I created so you can see what I was doing.
https://github.com/intervalia/proxyquire-215
It does pass tests. So I will dig further into my other code and let you know what I find.

But I really think it is my issue now and not yours.

**Comment by bendrucker** [comment]
😄 Thanks, that often happens with a repro, hopefully it's a helpful exercise!

**Comment by intervalia** [comment]
I figured out what happened that made me think this was a bug.

In my tests I was using `const proxyquire = require('proxyquire').noCallThru();`

I had assumed that since I was telling proxyquire to NOT use the original required code that it would not bother trying to load the original file.

In my test code I was telling the system to require a non-existent file. And Proxyquire complained that the file didn't exist.

To me this felt off since I didn't need it to exist in my tests. I was overriding it through a stub after all.

So it may not be a real bug, but it felt like one since I said `.noCallThru()`.

So maybe allow proxyquire to not bother checking to see if a file really exists when using `.noCallThru()` then my tests would not have failed.

Without change I now have to force the existence of a file, in my test environment, that is never used. If `.noCallThru()` didn't care about the existence of the required file then my code would have worked fine.

So maybe it is WAD, but it seems like a nice option to ignore the existence of any file that is stubbed out when using `.noCallThru()`

**Comment by bendrucker** [comment]
This is the output I get:

```
____ load.js loaded
Stubbed success.js called


  proxyquire issue #215 tests
TESTING Lazy loading files from ../lazyload/one
____ load.js run
loading ../lazyload/one
running ../lazyload/one
Stubbed one.js called
```

Proxyquire only tries to load the original to provide call-thru functionality. Setting `noCallThru()` should eliminate any need to have the stubbed modules actually present.

Please do modify your example if I'm misunderstanding since as long as the tests are passing I expect it's working.

**Comment by intervalia** [comment]
Sorry, I forgot to change my repo. It is now changed and shows the failure.

Again, this is a test only environment for me. I have a situation where I want to only stub out a file that does not exist. The code shows that. It used to require '../lazyload/one', which exists. Not it attempts to require '../lazyload/two' which does not exist but it 100% stubbed out in my test file (app.mocha.js).

**Comment by bendrucker** [comment]
Hmm, interesting. Looking into it.

**Comment by intervalia** [comment]
I'll check it within the hour.

**Comment by intervalia** [comment]
Yes. My bug is now gone. Thanks for the quick fix!!
