### ISSUE TITLE
Add support for ES Modules in Node.js

### ISSUE THREAD

**Issue by shanebloomer** [thlorenz/proxyquire#217]
Proxyquire does not work with ES Modules in Node.js.

```js
// a.mjs
import b from './b'

function run () {
  const result = b.add(1, 1)
  console.log(result)
}

export default {
  run
}
```

```js
// b.mjs
function add (numOne, numTwo) {
  return numOne + numTwo
}

export default {
  add
}
```

```js
// test.mjs
import proxyquire from 'proxyquire'
import sinon from 'sinon'
import test from 'tape'

test('a.run() should call b.add with 1 and 1', t => {
  const addSpy = sinon.spy()

  const a = proxyquire('./a', {
    './b': { add : addSpy }
  })

  a.run()

  t.deepEqual(addSpy.firstCall.args, [1, 1])
  t.end()
})
```

**Comment by bendrucker** [comment]
Hi, while ES modules (i.e. not enabled by default) I probably will not make time to work on adding it to proxyquire. Once its closer to stable it might require lots of internal and external (i.e. breaking) changes.

We'd certainly be interested in PRs and implementation discussion in the mean time.

**Comment by aladdin-add** [comment]
esm has been stable in node v12: https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#modules-ecmascript-modules

can you reopen the issue?

**Comment by stephencranedesign** [comment]
@bendrucker are you waiting for the esm loader spec to stabilize before you add esm support to proxyquire? Will proxyquire support esm mocking at some point or is it a big enough change that we will need to find a different library like [quibble](https://github.com/testdouble/quibble) to use for mocking esm modules?

**Comment by thlorenz** [comment]
proxyquire relies on `require` _extensions_.
Thus is the ESM Node.js implementation does not use those then proxyquire won't work.

I'm not sure how to provide the same functionality for ESM as I haven't had a closer look at how it is implemented.
However I'd love if someone digs into it and either creates an alternative that works for ESM or provides a PR to proxyquire to that end.

Unfortunately I personally don't have the bandwidth these times to look into something like this which afaik would be a major change.
