### ISSUE TITLE
Possible to reoverride modules that return a function?

### ISSUE THREAD

**Issue by Jeffphuang** [thlorenz/proxyquire#218]
If I have a module that exposes a function, Is there a way that I can override the initial stub?
```
module.exports = function () {
....
}
```

I noticed that if I have testing code like the following
```
var functionStub = function() {
    console.log('foo');
}
var index = proxyquire('./index', {'functionModule': functionStub}

[calling a test here prints 'foo']

functionStub = function() {
    console.log('bar');
}

[calling a test here still prints 'foo' instead of 'bar']
```

**Comment by bendrucker** [comment]
Hi, you're running into issues with references in JS! It doesn't matter that you say `functionStub =` later, you've already passed it _by reference_ to proxyquire. Assigning that variable name to a new reference later doesn't actually change the function that was passed in.

Instead, define your mock functions up front and `proxyquire` a new copy of the module for each new mock. How that looks will be pretty specific to your test framework. If you're having trouble feel free to post a broader example.
