### ISSUE TITLE
proxyquire throws cannot find module error whenever called without noCallThru()

### ISSUE THREAD

**Issue by Noor0** [thlorenz/proxyquire#221]
i'm using `proxyquire` with `jest` to test my serverless handler functions but i always get `Cannot find module '../../models' from '/User/.../signup`. This goes away if i call it with `const proxyquire = require('proxyquire').noCallThru()` but i don't want to stub out every module which is being used by my handler.

// handler.js
```
const { User } = require('../../models');

const shouldHave = require('../../utils/should-have');
const sendResponse = require('../../utils/send-response');

module.exports.signupHandler = async (event, context, callback) => {
     // using User model here to create a user in the DB
};
```

//test.js
```
const proxyquire = require('proxyquire');

const User = jest.genMockFromModule('../../../app/models/user');

const { signupHandler } = proxyquire('../../../app/handlers/signup', {
	'../../models': { User },
});

describe("it should signup user if the user doesn't exist", async () => {
	test("user doesn't exist", () => {
		const event = {
			body: {
				email: 'test1134@test.com',
				first_name: 'Test',
				last_name: 'User',
				username: 'test3123454',
				password: '12345678',
			},
		};

		const response = signupHandler(event);
		console.log(response);
	});
});
```

**Comment by bendrucker** [comment]
When used without noCallThru, proxyquire looks up any modules you try to stub to load their original implementation. Are you sure that path exists?

**Comment by bendrucker** [comment]
From your test, if you put `require('../../../app/handlers/signup')` above proxyquire, it succeeds? Just want to double check. It's a common mistake.

Otherwise, can I get the exact output?

**Comment by Noor0** [comment]
I'm not requiring the module, why do i have to `require` the module? doesn't `proxyquire` do that?
Anyway, i achieved what i wanted to achieve with `proxyquire` with `jest` using `jest.mock` and `jest.doMock`.

```
const User = require('../../../app/models/user');

jest.mock('../../../app/models/user');
const createSpy = jest.spyOn(User, 'create');

jest.doMock('../../../app/models', () => ({ User }));

const { signupHandler } = require('../../../app/handlers/signup');

...
// your test suite
...
```

**Comment by bendrucker** [comment]
Was looking for your help debugging. Sounds like you have something working with Jest and since it's an all-encompassing framework you should probably just stick with that.

**Comment by Noor0** [comment]
Thanks ben for replying and your help, i wasn't requiring the module in my test file because in the documentation it mentions that proxyquire imports the module that you're trying to test for you.

**Comment by bendrucker** [comment]
Right, in general a `proxyquire('./module-under-test', stubs)` call _should_ be replaceable by a `require('./module-under-test')`. That just means it shouldn't throw. That's only untrue if you're using proxyquire to provide a stub for a module that doesn't exit and using `noCallThru`. If `proxyquire` throws, the first step would be to ensure that an identical `require` doesn't.

**Comment by nohaibogdan1** [comment]
In my case, I am working on a Meteor app.  proxyquire doesn't find any module I give . I get this on mocha.
```

Error: Cannot find module '../HelperService'
    at Proxyquire._disableModuleCache (/home/cult/Documents/work/mindclash/microservices/api/node_modules/proxyquire/lib/proxyquire.js:273:19)
    at Proxyquire._disableCache (/home/cult/Documents/work/mindclash/microservices/api/node_modules/proxyquire/lib/proxyquire.js:241:15)
    at Proxyquire._withoutCache (/home/cult/Documents/work/mindclash/microservices/api/node_modules/proxyquire/lib/proxyquire.js:199:27)
    at Proxyquire.load (/home/cult/Documents/work/mindclash/microservices/api/node_modules/proxyquire/lib/proxyquire.js:129:15)
    at Hook.<anonymous> (src/api/modules/accounts/AccountService/__tests__/HelperService.test.js:146:29)
    at run (packages/practicalmeteor:mocha-core/server.js:34:29)
```
