### ISSUE TITLE
Can't proxyquire json files in v2

### ISSUE THREAD

**Issue by wheresrhys** [thlorenz/proxyquire#224]
This appears to be similar to this issue https://github.com/thlorenz/proxyquire/issues/137.

Here's a code sample:

```
	const fetchMock = require('fetch-mock').sandbox();
	const update = proxyquire('../../lib/update-biz-ops', {
		'../v2/services.json': [],
		'./biz-ops-client': proxyquire('../../lib/biz-ops-client', {
			'node-fetch': fetchMock
		})
	});
```

It works in v1.7, so all the paths etc are configured correctly.

I wonder if the problem might be caused by the nested proxyquires as I imagine you have tests to cover the simplest case of a single proxyquire that uses a json?

I've tried with `noPreserveCache()` and `noCallThru()`, to no avail

**Comment by bendrucker** [comment]
Do you get an error or is services not `[]`?

**Comment by wheresrhys** [comment]
It requires the real json file, as if proxyquire isn't there. I added logs here https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L167 (maybe not the most useful place, but just poking around), and lots of module names were logged out, including IIRC all the ones mentioned in the code sample above, but none of the lines logged ended `v2/services.json`
