### ISSUE TITLE
proxyquire not stubbing module function

### ISSUE THREAD

**Issue by samuela** [thlorenz/proxyquire#236]
Check out this PR (https://github.com/oclif/config/pull/70) at this commit (https://github.com/oclif/config/pull/70/commits/eb4b9156e5a5e887e364342c23596deff3f27790). The `ts-node.ts` module looks something like:
```typescript
function registerTSNode(root: string) {
  const tsconfig = loadTSConfig(root)
}

function loadTSConfig(root: string): TSConfig | undefined {
  console.log('loadTSConfig unstubbed')
  // function to be stubbed...
}

export function tsPath(root: string, orig: string | undefined): string | undefined {
  registerTSNode(root)
}
```
and I'm requiring it with proxyquire as follows:
```typescript
const stubLoader = (_: any) => {
  console.log('loadTSConfig proxyquire')
  return config
}
const tsNodePlugin = proxyquire('../src/ts-node', {'loadTSConfig': stubLoader})

// This prints "loadTSConfig unstubbed" not "loadTSConfig proxyquire"!
tsNodePlugin.tsPath('poop', 'asdf')
```
But unfortunately proxyquire is not actually injecting `stubLoader` into the module as expected.

I've tried:
* Exporting all of the functions in `ts-node.ts`
* Calling  `tsNodePlugin.registerTSNode`, and even `tsNodePlugin.loadTSConfig` directly
* Adjusting the stub key: '.loadTSConfig', './loadTSConfig', etc
* Clearing the cache with `delete require.cache[require.resolve('../src/ts-node')]`
all to no avail.

**Comment by bendrucker** [comment]
Hi, proxyquire operates on _modules_, and not by munging your local scope within a module. You can't stub something in the local scope of the module under test. You _can_ stub something that your module under test _requires_. We believe this is important to maintainable tests. 

If your tests can manipulate the local variables of modules under test, there is no isolation between your tests and your source code. Changing an internal function name within your source code should not break tests.

If you'd like to use proxyquire, I'd recommend pulling that function out to its own module. You'll then stub it by its path relative to the module under test, and not its identifier (which is private).

```js
proxyquire('../src/ts-node', {'./load-ts-config': stubLoader})
```

**Comment by samuela** [comment]
Understood, thank you for the quick response.
