### ISSUE TITLE
proxy a dependency which requires a constructor

### ISSUE THREAD

**Issue by cassiodias** [thlorenz/proxyquire#242]
Hello, my component under test has a dependency which requires a configuration object

```
const dependency = require('lib-id')(configuration);

function getSomething(){
  return dependency.method();
}
```

When I am testing my component, I am trying to proxy this dependency, but it's not working giving the error **require(...) is not a function** 

```
const serviceUnderTest = proxyquire('../MyService.js',
  {
    'lib-id': { // here is my dependency with the require('lib-id')(config)
      method: () => 'dummyString',
    },
  }
);

describe('Test', () => {
  it('Should mock dependency', () => {
    const expected = 'dummyString';
    const ttr = serviceUnderTest.getSomething();
    expect(ttr).to.equal(expected);
  });
});
```

I have different components and tests using proxyquire and they work really well, but none of them require arguments in the **require('')** definition.

Is there a different process in that case? The lib I am trying to proxy has the following definition at the export level:

```
module.exports = (config) => {
....
```

Thanks for any help!

**Comment by bendrucker** [comment]
`require('lib-id')` should return a function that returns an object, but you're setting it to an object. Try something like this:

```js
proxyquire('../MyService.js', {
  'lib-id': () => ({
    method: () => 'dummyString'
  })
})
```

**Comment by cassiodias** [comment]
Awesome, thx @bendrucker !

**Comment by cassiodias** [comment]
Hi @bendrucker, is there a way to preserve the original methods? This solution is returning a whole new object

**Comment by bendrucker** [comment]
Proxyquire can't help you, you export a function that returns an object and are using proxy quire to replace that function. You'd have to do something like this:

```js
const original = require('lib-id')
proxyquire('../MyService.js', {
  'lib-id': (/* config */) =>({
    method: () => 'dummyString',
    ...original()
  })
})
```

Not tested, but hopefully you get the picture

**Comment by cassiodias** [comment]
FYI it works
