### ISSUE TITLE
Stubbing multiple requests with proxyquire

### ISSUE THREAD

**Issue by Tyzanol** [thlorenz/proxyquire#251]
Is there a way of stubbing 2 or more requests with proxyquire?

For example, 
Say I have a file called file.js
```
{
  module.exports = function methodA() { 
    return doSomething;
 };
  module.exports = function methodB() { 
    return doSomething;
 };
  module.exports = function methodC() { 
    return doSomething;
 };
}
```

If I'd like to mock 2 methods so that they react with the same mock - 

testFile.js
```
{
  pathStub = {}
  proxyquire('./methodA', { 'path': pathStub });
  proxyquire('./methodB', { 'path': pathStub });
}
```

Is this possible?

**Comment by bendrucker** [comment]
The code you've supplied doesn't make sense to me. You've assigned `module.exports` three times in your source code and only the last has any effect. 

That said, proxyquire proxies things that your module under test requires. Not specific functions.
