### ISSUE TITLE
Using `@global` on path with subdir causes Node to throw MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by ryanblock** [thlorenz/proxyquire#257]
Hey! Long time fan and user of this lib, first time caller. ✨

I was having a lot of trouble using `@global` in a certain case, and believe it's possible there's a `proxyquire` issue lurking in there.

I've created a reduced test case repo based on the main [`@global` example in the readme](https://github.com/thlorenz/proxyquire#globally-override-require-during-module-initialization): https://github.com/ryanblock/proxyquire-path-bug-reduced-test-case

This demonstrates the issue:
- When using `proxyquire` with `@global` against a module in the same folder (e.g. `./foo`), things work fine
- However, when using `proxyquire` with `@global` against a module that resolves to the same name in a different folder (e.g. `./foo` for `./foo/index.js`, or even `./foo/index.js` literally), Node throws a `MODULE_NOT_FOUND` error

I am running Node.js v12.18.3 on macOS Catalina.

Hope that helps, please let me know if you require (ha) any other information or repro steps.

**Comment by bendrucker** [comment]
Hmm, definitely looks like a bug. May be a little while but I'll try to look into this.

**Comment by ryanblock** [comment]
@bendrucker right on – if open to a PR and want to point me in the right direction, I may be able to lend a hand.

**Comment by bendrucker** [comment]
Presumably this is a case of modules needing to be resolved first to their canonical location rather than just treated as literal strings. Here's an example of that resolution happening:

https://github.com/thlorenz/proxyquire/blob/master/lib/proxyquire.js#L137-L141

Guessing no one's noticed this before since global overrides are most common with global packages.

**Comment by bendrucker** [comment]
Hmm on second look this isn't valid:

https://github.com/ryanblock/proxyquire-path-bug-reduced-test-case/blob/main/borken/bar/index.js#L1

It's the opposite of what I was alluding to above. Proxyquire _is_ correctly trying to resolve the module path. Stubbing `./baz` refers to a module relative to the module under test, not any module in the require tree that has a literal call to `require('./baz')`. It should be:

```js
var baz = require('../baz');
```

And after making that change the test passes.
