### ISSUE TITLE
Examples of use with classes

### ISSUE THREAD

**Issue by blmille1** [thlorenz/proxyquire#259]
I have been searching all day so far as to how to proxyquire a module that returns a class and still don't have a working example.
I've looked through other issues here and tried to use them.
I could show you what I have, but there's a lot to it and I think just having a working sample would clear things up.

Here's an incomplete snippet just in case it helps:
```js
// test
const proxyquire = require('proxyquire').noCallThru();
const stub = sinon.stub().resolves();
class FakeDlqIterator {
    constructor() {
        this.args = arguments;
    }
    async iterate() {
        return await stub(arguments);
    }
}
FakeDlqIterator['@noCallThru'] = true;

proxyquire('../../../lambdas/maintenance/dlq-iterator', {
    './dlq-iterator': FakeDlqIterator
});
const dlq = require('../../../lambdas/maintenance/dlq');
// dlq news up the original dependency and not the fake...
```

```js
// ../../../lambdas/maintenance/dlq-iterator
class DeadLetterQueueIterator {
    constructor(queueUrl, visibilityTimeout = 900) {
        // initialize stuff
    }
    async iterate (filters, isClear) {
       // lots of cool things happen here
    }
}

module.exports = DeadLetterQueueIterator;
```

**Comment by blmille1** [comment]
I'm using Node `12.18.1` if that helps.

**Comment by bendrucker** [comment]
Contributions via pull requests are welcome. Proxyquire overrides normal require semantics _while executing_. That means that something that looks like this is wrong:

```js
proxyquire('../../../lambdas/maintenance/dlq-iterator', {
    './dlq-iterator': FakeDlqIterator
});
const dlq = require('../../../lambdas/maintenance/dlq');
```

You should be using the return value of proxyquire and not attempting to use it to trigger side effects.
