### ISSUE TITLE
Cannot proxy module sub-item

### ISSUE THREAD

**Issue by guycnicholas** [thlorenz/proxyquire#260]
We have code that is shared among a number of servers.
```
// shared node_module code
exports.version = '1.0.0';

exports.item1 = require('./<path to item1');
exports.item2 = require('./<path to item2');
```

Then my server code has something like this:
```
const item1 = require('shared-code').item1;
```
I am unable to figure out how to proxyquire item1 as I can't get its path.  I can do a require.resolve('shared-code') but then am not sure what I would need to do to get the path of item1.

**Comment by bendrucker** [comment]
> I am unable to figure out how to proxyquire item1 as I can't get its path.

This is the central requirement of how proxyquire works. It overrides dependencies by module path. If you don't know the shape of the module you're overriding it's not possible to use proxyquire. Not sure how that's possible (dynamic module paths?).

Perhaps you should just mutate that shared object directly or with a utility like Sinon. Seems like proxyquire may not be the right tool for what you're trying to do.

**Comment by bendrucker** [comment]
Closing as a support request but happy to try to continue discussing if you want to share concise examples

**Comment by guycnicholas** [comment]
@bendrucker thanks for the reply. I ended up figuring it out:
```
class MockItem1 {...} 
const testedCode = proxyquire('TestedCode', {
	shared: {
		Item1: MockItem1,
		Item2: MockItem2
	},
	...
}

TestedCode.js
const Item1 = require('shared').Item1;

class TestedCode {
    const item1Instance = new Item1(); // this calls my MockItem1 code

}

```
