### ISSUE TITLE
Unable to resolve module `module` from `node_modules/proxyquire/lib/proxyquire.js`

### ISSUE THREAD

**Issue by warunacds** [thlorenz/proxyquire#263]
I'm getting the following error on a to react native project.  It used to work fine but then I got this error without me making any changes to the project. Check the file location, it's there and permission is adequate. 

`Error: Unable to resolve module `module` from `node_modules/proxyquire/lib/proxyquire.js`: module could not be found within the project.`

I delete watchman cache, remove node_modules and rebuild the project but non of them worked.

**Comment by bendrucker** [comment]
Sounds like this could be a React Native issue. Proxyquire only targets Node and mileage will vary in any Node-like environment. Feel free to share additional info for others on this thread but it sounds unlikely that we can fix this.
