### ISSUE TITLE
Stubbing a dependency within a base class

### ISSUE THREAD

**Issue by oldschoolbg** [thlorenz/proxyquire#266]
I am working with some legacy code that has the following structure:

**Class I am testing:**
```
class ConcreteClass extends FirstBaseClass {
    constructor() {
       super(thing, thing, thing);
    }
}

```
**First level of inheritance**
```
module.exports = class FirstBaseClass extends SecondBaseClass{
    constructor(thing, thing, thing) {
       super(thing, thing, thing)
    }
}
```

**Second level of inheritance**
```
const commandLineArgs = require('command-line-args');

module.exports = class SecondBaseClass{
    constructor(thing, thing, thing) {
        const args = commandLineArgs({});
    }
}

```

I am attemping to use proxyquire to replace the require in the 2nd level of inheritance and have made a couple of attempts but none of them result in a proxied require:

**Attempt 1**
```
var stubbedConcrete = proxyquire('../path/to/concrete/file', {
        "command-line-args": function (argsDefinition) {
          console.log(argsDefinition);
          console.log('hitting the stub');
        }
      });
const concrete = new stubbedConcrete();
```

**Attempt 2**
```
var stubbedConcrete = proxyquire('../path/to/concrete/file', {
        "command-line-args": (argsDefinition) => {
          console.log(argsDefinition);
          console.log('hitting the stub');
        }
      });
const concrete = new stubbedConcrete();
```

No matter what I try I am seeing my code calling the "real" command-line-args and not my stub.

How would I go about achieving this? I've searched through the closed issues, stackoverflow, etc and I cannot find anything that addresses this. Any help very gratefully received.

Thanks in advance.

**Comment by bendrucker** [comment]
You need the `@global` option enabled for that dependency. See the readme for examples. Proxyquire normally only overrides direct dependencies of the subject under test, ensuring that tests do not implicitly manipulate internals of dependencies.

**Comment by oldschoolbg** [comment]
Thank you - this did solve the issue indeed. Appreciate your help.
