### ISSUE TITLE
proxyquire jasmine expect not working - 1 test 0 assertions

### ISSUE THREAD

**Issue by Fabiomad85** [thlorenz/proxyquire#267]
I am working with proxyquire for mock some requirement on my module. It is working fine.

I added one expect as always
 
`expect(expectOutputData.data).toBe(outputData.data);`

but inside my jasmine suite,  i have this message:

`
Finished in 0.166 seconds
1 test, 0 assertions, 0 failures, 0 skipped
`

this is not correct. Like somehow  the proxyquire messes with the assertion.

**Comment by bendrucker** [comment]
This seems like a support request and not a bug. If you'd like help with the former we absolutely need a reproducible project example.

**Comment by Fabiomad85** [comment]
The problem was Jasmin version that doesnt not support the async/await. thanks anyway
