### ISSUE TITLE
How to use multiple ways to override the imported function in controller using proxyquire

### ISSUE THREAD

**Issue by rruichava** [thlorenz/proxyquire#268]
Hi, I am using proxyquire to override the dependencies but having some confusion how to override one imported function in different situations. Can you please help below query
[https://stackoverflow.com/questions/70866210/sinon-stub-and-proxyquire-is-not-working-as-excepted](https://stackoverflow.com/questions/70866210/sinon-stub-and-proxyquire-is-not-working-as-excepted)

**Comment by bendrucker** [comment]
Sorry issues are for library problems not support. Make sure your override module paths match, it's a common mistake.
