### ISSUE TITLE
Stubbing peer dependencies

### ISSUE THREAD

**Issue by jankapunkt** [thlorenz/proxyquire#269]
I have (optional) peer dependencies and I don't want to add them as dev-dependencies but want to test them anyway, so I thought I can just stub them using noCallThru, but it seems, that it is stll required to install that dependency?

```js
const proxyquire =  require('proxyquire').noCallThru();
const stub = require('./path/to/mystub')
proxyquire('./path/to/projectmodule', { 'npmmodule': stub });
```

I get 

```
Error: Unable to read/parse /path/to/project/.mocharc.js: Error: Cannot find module 'npmmodule'
```

Did I misunderstood how it's suppoed to work?

**Comment by bendrucker** [comment]
If you are overriding a dependency of a module in your project, by definition that is not a peer dependency. 

If you are overriding a transitive dependency that requires the `@global` option. 

If that's not the issue we'll need a fully reproducible example.

**Comment by bendrucker** [comment]
A peer dependency is a dependency of another npm package you depend on. By definition, a module that you require relatively cannot directly require a peer dependency.

Given the above, this seems like a support/usage issue. If you can demonstrate a bug through runnable code I will of course reopen. Argumentativeness will not be tolerated though.
