### ISSUE TITLE
Proxyquire compatibility with ESM

### ISSUE THREAD

**Issue by IsaacChaverri** [thlorenz/proxyquire#271]
Hello!
We are currently using Proxyquire to run tests with our apps, which means we have a large dependency on Proxyquire, and we were wondering what the future holds for ESM in regards to Proxyquire. Is there a plan to add ESM support to Proxyquire? And if so, is there an estimated date for this?

**Comment by bendrucker** [comment]
https://github.com/thlorenz/proxyquire/issues/217#issuecomment-1143690177
