### ISSUE TITLE
Cannot read property 'require' of undefined when using ES6 modules

### ISSUE THREAD

**Issue by springcomp** [thlorenz/proxyquire#274]
Here is [a minimal repro case](https://github.com/springcomp/proxyquire-es6-issue).

**Comment by bendrucker** [comment]
Proxyquire works with `require` only and doesn't support ES Modules.

**Comment by springcomp** [comment]
Thanks for the feedback.

**Comment by pabx06** [comment]
I Have the same issue.

**Comment by sokraflex** [comment]
Same here. This forces us to switch to another library.

**Comment by damusix** [comment]
@sokraflex I looked into this earlier this year and I don't think anyone can support stubbing ESM imports by transforming them into CJS. IIRC, it seems like everything that transpiles into CJS from ESM implements the literal standard, which is to return your module as a getter only, which means it's never allowed to be set. You'll never get to stub.
