### ISSUE TITLE
module exporting a function

### ISSUE THREAD

**Issue by erakis** [thlorenz/proxyquire#275]
Hi,

I need to replace the function returns by a module. 

I'm using **CommonJS** with **nodejs 18**.

Here is the required module

```js
module.exports = async () => {
  return "Hello world NOT to call";
};
```

Here is how I proxied it 
```js
const sinon = require("sinon");
const proxyquire = require("proxyquire").noCallThru();

async function main() {
  const stubbedFunction = sinon.stub().resolves(() => "Hello stubbed world");
  const requiredModuleStubbed = proxyquire("./my-required-module", {
    "./my-required-module": stubbedFunction,
  });
  const message = await requiredModuleStubbed();
  console.log(message);
}

main();
```

The problem is that the output is the one that should not be called!

```
Hello world NOT to call
```

instead of the proxied one

```
Hello stubbed world
```

[Here's a codesandbox example](https://codesandbox.io/p/sandbox/agitated-night-4dt8ll)

_Note that I cannot modify the source code of the required module to add a name to it. Otherwise, I would have already done it._

**Comment by bendrucker** [comment]
This doesn't make sense:

```js
  const requiredModuleStubbed = proxyquire("./my-required-module", {
    "./my-required-module": stubbedFunction,
  });
```

Note the repetition. Proxyquire is for replacing things that your source modules require. Your source module requires nothing.
