### ISSUE TITLE
noPreserveCache doesn't seem to work in 1.0.0

### ISSUE THREAD

**Issue by davejhilton** [thlorenz/proxyquire#35]
Somewhere between 0.6.0 and 1.0.0, the noPreserveCache function no longer appears to be doing what the documentation says it will do. 

I have a situation similar to the one described in #25— Imagine I have the following files:

**foo.js:**

```
exports.bar = function() {
  return 'real';
};
```

**usesFoo.js:**

```
var foo = require('foo');
exports.baz = function() {
  return foo.bar() + ' thing';
};
```

**usesFooUnitTest.js:**

```
var proxyquire = require('proxyquire').noPreserveCache();
var usesFoo = proxyquire('usesFoo', {
  'foo': {
    bar: function() {
      return 'fake';
    }
  }
});
expect(usesFoo.baz()).to.equal('fake thing'); // test passes
```

**integrationTest.js:**

```
var usesFoo = require('usesFoo');
expect(usesFoo.baz()).to.equal('real thing'); // test fails! returns 'fake thing'
```

Since I have a grunt build that runs unit tests immediately followed by integration tests, my build fails on the integration tests as shown above.  If I just run integration tests in isolation, they pass just fine.  Also, if I change my package.json to use proxyquire 0.6.0, my build also passes.

Obviously understanding that any 0.x.x version may not yet have a hardened API... I'm wondering: was this an intended breaking change when moving to 1.0, and the documentation is just out of date?  Or is this a regression? If it's the latter, is there a suggested workaround?

Thanks!

**Comment by webteckie** [comment]
Instead of opening a new issue, I'll post here just in case my setup is wrong.  I'm using the latest (just upgraded from 1.5.0, which also seem to have the same issue).  The noPreserveCache() appears not to be working for me:

Have a bunch of unit test modules that start with:
```
var proxyquire = require('proxyquire').noCallThru().noPreserveCache();
var keystoneStub = proxyquire('keystonejs-stub',{});
```

keystonejs-stub is basically just:
```
function Keystone() {
  console.log("****NEW KEYSTONE INSTANCE****");
  ...
}

module.exports = new Keystone();
```

When my unit tests run I only see a single "****NEW KEYSTONE INSTANCE****" logged.  Shouldn't a new Keystone instance be exported every time a do a proxyquire on the keystonejs-stub module per the noPreserveCache() option?

**Comment by bitsoflogic** [comment]
@webteckie Consider this setup...

keystone.js
```
function Keystone() {
  console.log("****NEW KEYSTONE INSTANCE****");
}

Keystone.prototype.isOverriden = function() {
  return false;
}

module.exports = new Keystone();
```

keystone-caller.js
```
var ks = require('./keystone');

module.exports.isProxied = ks.isOverriden();
```

test/keystone-test.js
```
var proxyquire = require('proxyquire').noPreserveCache();
var should = require('should');

describe('test', function() {
    it('will pass once', function() {
        var kc = proxyquire('../keystone-caller', {
            './keystone': {
                isOverriden: function() {
                    return true;
                }
            }
        });

        kc.isProxied.should.equal(true);
    });

    it('will pass twice', function() {
        // Could be called this way: var kc = proxyquire('../keystone-caller', {});
        var kc = require('../keystone-caller');
        
        kc.isProxied.should.equal(false);
    });
});
```

Without using `noPreserveCache` the second test would fail.  By using it, it calls a `delete require.cache...` on `keystone-caller.js`.  This forces the `keystone-caller.js` to make a fresh call to the `keystone.js` file when it is used next.  The `keystone.js` file does not need to be refreshed in the require.cache for this to work, so you only end up with a single `console.log` call.
