### ISSUE TITLE
Stub not overriding original

### ISSUE THREAD

**Issue by ghachey** [thlorenz/proxyquire#42]
Hi,

I realize I'm probably doing something wrong, but I've tried several things and no matter what I do I can't get my stubbed function to run within my module under test. I have no problems when experimenting with variations of provided samples including the sinon one. I'm hoping a more experienced pair of eyes could help me out a little.

Module under test with nano, the couchdb module dependency I want to mock.
```
var async = require('async');
var db = require('nano')('http://localhost:5984/mydb');

module.exports.getDocs = function(docs, callback){
  // some logic
  async.map(docs, function(doc, cb) {
    db.get(doc, function(err, body) {
      cb(err, body);
    });
  }, function(err, results) {
    if (err) {
      callback(err, null);
    } else {
      callback(null, results);
    }
  });
};
``` 
Test using proxyquire and sinon.
```
var proxyquire = require('proxyquire');
var sinon = require('sinon');
var db = require('nano')('http://localhost:5984/mydb');
var couchdb; // import using proxy below

describe('CouchDB document model', function(){
  var getStub;

  before(function () {
    getStub = sinon.stub(db, 'get');
    couchdb = proxyquire('../../../app/models/couchdb', { db: {get: getStub} });
    getStub.yields({'some': 'data'});
  });

  after(function () {
    db.get.restore();
  });

  describe('getDocs function', function(){
    it('should use fake couchdb data', function(done) {
      couchdb.getDocs(docs, function(err, body) {
        // Getting body with data from real CouchDB, i.e. original db.get is called
        done();
      });
    });
  });

});
```

**Comment by bendrucker** [comment]
Closing this as it's not clear what's going on here

**Comment by chrissharp80** [comment]
@bendrucker it's very clear what's going on. He was trying to stub the `use` function of the `nano` library. And no one helped. Now I'm facing the same problem, 5 years later, and I find this issue, with my exact problem closed with no answer besides "read the docs" and "it's not clear". It would be great to actually get someone to try to stub out a function in `nano` and see what happens. Thanks.
