### ISSUE TITLE
Support for node-webkit?

### ISSUE THREAD

**Issue by vasanthps** [thlorenz/proxyquire#54]
We have a node-webkit app, that has angularjs services and we 'require' node modules inside them. These files do not have any module.exports. We are writing unit test cases and we want to mock the require's present in these files. Any plan to support this case in future?

Thanks

**Comment by yoshuawuyts** [comment]
I've used `nw.js`/`node-webkit` with `proxyquire` in the past. I don't completely understand what you're doing, but it should be possible to use them together.

**Comment by vasanthps** [comment]
<B>foo.js</B>
```javascript
mainApp.service('demoService', function() {

var path = require('path');
     this.demoFn = function() {
          var customMod = require('custom-module');
     };
});
```

Would I be able to proxyquire the require's present in foo.js for unit testing?

**Comment by bendrucker** [comment]
Sure, just do `proxyquire('./foo'. {'custom-module': stub})`

Not sure what I'm missing here — nothing special about this case.

**Comment by vasanthps** [comment]
The difference is:-
1. Unit tests are run in node-webkit environment
2. The foo.js does not have module.exports, because it is angular (client) code clubbed with v8 code, this would run fine in nw.

**Comment by bendrucker** [comment]
Neither of those helps us understand whether you've tried this and if so why it's not working.

**Comment by thlorenz** [comment]
@vasanthps if it's not using `require` it won't work with proxyquire since that depends on `require` extensions.
You'd need to find another tool for your case.

**Comment by vasanthps** [comment]
@thlorenz Thanks :)
