### ISSUE TITLE
@noCallThru with modules that export a single function?

### ISSUE THREAD

**Issue by raine** [thlorenz/proxyquire#55]
How can you pass `{ @noCallThru: true }` in case of

```js
var foo = proxyquire('./foo', {
  '../module: module-stub
});
```

Cheers.

**Comment by thlorenz** [comment]
Explained in detail in the docs, please reread them.

**Comment by raine** [comment]
Are you referring to `proxyquire.noCallThru()` because that's the only thing I could find, and that changes proxyquire globally which is not a nice thing.

**Comment by thlorenz** [comment]
Please carefully read [this](https://github.com/thlorenz/proxyquire#preventing-call-thru-to-original-dependency). That shows per stub `@nocallthru`.

**Comment by raine** [comment]
Hmm, are we on the same page?

I'm sorry if I wasn't clear but in this case `../module` is something that directly exports a function with `module.exports`. Therefore you can't give an object with `@noCallThru` in `{ '../module': moduleStub }`.

I ended up wrapping my `proxyquire` call with `proxyquire.noCallThru()` and `proxyquire.callThru()` to resume the original behavior.

**Comment by thlorenz** [comment]
All you need to add is that `@noCallThru` property, how is not important.
`moduleStub[@noCallThru] = true` should work.

**Comment by raine** [comment]
Makes sense. Thanks for patience!
