### ISSUE TITLE
Globally override a module that returns a function

### ISSUE THREAD

**Issue by TheSavior** [thlorenz/proxyquire#56]
I know that you can set `'@global': true` in the stubs for modules that are objects, but how do you do it for modules that return functions. For example:

```javascript
// main.js
var Deep = require('./deep');

var instance = new Deep();
instance.run();

module.exports = instance;
```

```javascript
// deep.js
var deepest = require('./deepest')('My Name');

function Deep() {
}

Deep.prototype = {
  run: function() {
    deepest.baz();
  }
};

module.exports = new Deep();
```

```javascript
// deepest.js
function Deepest(name) {
  return {
    baz: function() {
      console.log(name);
    }
  };
}

module.exports = Deepest;
```

Deepest returns a function that I need to mock out, but since it is used inside of Deep, I have to use `@global`.

If deepest was exporting the inner object instead of the wrapping function, I could do this:

```javascript
var main = proxyquire('./main.js', {
  './deepest': {
    '@global': true,
    'baz: function() {}
  }
}
```

But since deepest returns a function, my understanding is that I have to mock it like this:
```javascript
var main = proxyquire('./main.js', {
  './deepest': function() {
    return {
      baz: function() {
        console.log('mocked');
      }
    }
  }
}
```

But I can no longer set '@global' on the mock object. Right? How should I handle this? This situation has arisen because of the api design of a third party module so I sadly can't really restructure these calls.

**Comment by bendrucker** [comment]
Sure you can! Just assign create a function assigned to a variable and then set `deepest['@global'] = true`. 

```js
var deepest = function () {}
deepest['@global'] = true
```

**Comment by TheSavior** [comment]
Neat. Thanks!

**Comment by thlorenz** [comment]
Seems like we need to add these special cases to the docs and/or a wiki.

**Comment by bendrucker** [comment]
Sure. I think it merits its own section under `API`. Wikis don't actually get read. Agreed?

**Comment by thlorenz** [comment]
Agreed, currently we don't even have a wiki to speak of :)

**Comment by MarkHerhold** [comment]
@bendrucker This `'@global' = true` implementation of yours is truly genius! :+1:
