### ISSUE TITLE
Doesn't seem to be overriding require?

### ISSUE THREAD

**Issue by rizowski** [thlorenz/proxyquire#59]
I am not sure what is going on but I have been trying multiple mocking/require hijacking libraries to see if I can mock some of my dependencies. I like proxyquire but the problem being proxyquire doesn't seem to be giving me my mocked objects.

```javascript
// item.js
var parser = require('./parser');

module.exports = {
  someFunctionThatUsesParser: function(){ ... };
}
```

```javascript
// item-spec.js
var proxy = require("proxyquire"),
  item;
//jasmine before each
beforeEach(function(){
  var mock = {
    'parser' : {
      myMockedFunction: function(){ ... }
    }
  };
  item = proxy("../src/item", mock);
});
// tests below
```

Folder structure is:
```
project/
  |- src/
  |--- item.js
  |--- parser.js
  |- spec/
  |--- item-spec.js
```
Is that not the way this is supposed to be set up? I have checked to see if the `parser` object that `item` uses vs what I have mocked are the same object and they are not. Any Ideas?

**Comment by bendrucker** [comment]
The keys in the proxyquire call's second arg need to match the requires in your source code. 

```js
var mock = {
    './parser' : {
      myMockedFunction: function(){ ... }
    }
  };
```

**Comment by redixhumayun** [comment]
This really needs to be mentioned more explicitly in the documentation that the key needs to be the exact same as the require path in your module.
