### ISSUE TITLE
How to reset/un-mock the mocked dependency in proxyquire?

### ISSUE THREAD

**Issue by sarbbottam** [thlorenz/proxyquire#61]
File structure:
---
```
.
|____lib
| |____bar.js
| |____baz.js
| |____foo.js
|____test
| |____bar.js
| |____baz.js
| |____foo.js
```
Use case:
---

With respect to the above file structure, `./lib/foo.js` requires `./lib/bar.js`, `./lib/bar.js` requires `./lib/baz.js`.

---

While unit testing `./lib/foo.js` via `./test/foo.js`, I would like to mock `./lib/bar.js`, so that, I am only concerned with `./lib/foo.js`.
Once the tests in `./test/foo.js` are over I would like to reset/un-mock `./lib/bar.js`.

While unit testing `./lib/bar.js` via `./test/bar.js`, I would like to mock `./lib/baz.js`, so that, I am only concerned with `./lib/baz.js`. 
Once the tests in `./test/foo.js` are over I would like to reset/un-mock `./lib/baz.js`.

So on and so forth.

---

Or in other words, I would like to mock the dependencies and reset as and when required, in the test file. 

Most likely mocking several times in the test file and reseting a after all the test are over in a test file.

Or may be I can control the local mock, with some file level closure variables

---
Looks like [mockery](https://www.npmjs.com/package/mockery) addresses my use-case, mainly [reset/un-mock the mocked dependency](https://github.com/mfncooper/mockery#deregistering-everything).

How to achieve the same in [proxyquire](https://www.npmjs.com/package/proxyquire)?

**Comment by bendrucker** [comment]
I don't really know how mockery works, but proxyquire offers what I see as a dramatically more useful and sensible API. Because you pass the stubs as part of the `proxyquire` call, your stubs don't leak out and require explicit deregistration as with mockery.

```
// test/foo.js

var foo = proxyquire('../lib, {
  './bar': barStub
})
```

**Comment by bendrucker** [comment]
And if you need to prevent the modules themselves from being cached (i.e. the first argument to `proxyquire`) you can control the require cache:

https://github.com/thlorenz/proxyquire#forcing-proxyquire-to-reload-modules

**Comment by sarbbottam** [comment]
Thanks @bendrucker
