### ISSUE TITLE
Support for Webpack?

### ISSUE THREAD

**Issue by jakubholynet** [thlorenz/proxyquire#62]
Hello,

Thanks for this great library! I wonder whether there are any plans to support also Webpack in addition to Browserify. How large job is it to add support for it?

Thank you!

**Comment by jakubholynet** [comment]
I see that [rewire](https://github.com/jhnns/rewire) runs on Node but also [supports webpack](https://www.npmjs.com/package/rewire-webpack) so may be that is a reasonable option? (Though I prefer proxyquire's API)

**Comment by thlorenz** [comment]
Have a look at [proxyqurieify](https://github.com/thlorenz/proxyquireify) and [proxyquire-universal](https://github.com/bendrucker/proxyquire-universal). 
They work with browserify via plugin or transform.
Not sure if webpack supports that.

FWIW all this is explained in the [first paragraph of the README](https://github.com/thlorenz/proxyquire#proxyquire-)

**Comment by bendrucker** [comment]
No plans to support Webpack specifically since neither of us use it. If someone really wanted to invest the time I'd be willing to help offer guidance. Otherwise it's just not very high on my list.

I'd really recommend not using rewire. Using eval to write unit tests is a really bad idea in principle, but it can also create a ton of compatibility headaches as well. Most transpilers (e.g. Babel) can change your variable names and then everything breaks.

**Comment by jakubholynet** [comment]
Thank you. I have looked briefly at the code of proxyqurieify, proxyquire-universal, and rewire-webpack and it seems to be no simple matter to port proxyquire to a new build tool so I guess I will need to use rewire :-(

**Comment by thlorenz** [comment]
Actually this is a good reason to switch to browserify.
We are opinionated obviously, but it's modular plugable nature makes packages like proxyquireify possible.
Or you stick with webpack until you run into the next nice thing you can't have ;)

**Comment by jedrichards** [comment]
Just noticed a new Babel plugin inspired by rewire. Thought it might be of interest: https://github.com/speedskater/babel-plugin-rewire

**Comment by volkanunsal** [comment]
I'm coming here after trying the Babel plugin. It doesn't support function imports. I had high hopes for this library, but I can't use it without Webpack support.

**Comment by djskinner** [comment]
This may be useful for Webpack users looking for proxyquire-like functionality: https://github.com/plasticine/inject-loader
