### ISSUE TITLE
Proxyquire Failing to load stubbed content

### ISSUE THREAD

**Issue by seanzx85** [thlorenz/proxyquire#67]
Hi,

I really like using proxy quire but I have been running into a strange issue.  When i stub a required object, the original is loaded.  If i npm remove the object it throws 'Cannot find module'.  So i created the smallest use case for this.

File: demo.js
```
var _ = require('lodash');

module.exports.test1 = function() {
  return _.sum([1, 2]);
};

var doesNotExist = require('doesNotExist');

module.exports.test2 = function() {
  return doesNotExist.test();
};
```

Test Case: demo.spec.js

```
var proxyquire = require('proxyquire'),
  chai = require('chai'),
  expect = chai.expect;

function setup() {
  return proxyquire('./demo', {
    lodash: {
      sum: function(arr) {
        var total = 0;
        arr.forEach(function(num) {
          total += num;
        });
        return total + 'test';
      }
    },
    doesNotExist: {
      test: function() {
        return true;
      }
    }
  })
}

describe('Test Proxyquire', function() {
  it('should handle lodash override correctly', function() {
    var test = setup();
    expect(test.test1([1, 2])).to.be.equal('3test')
  });

  it('should handle doesNotExist correctly', function() {
    var test = setup();
    expect(test.test2()).to.be.equal('proxy worked');
  });
});
```

run 
```
npm install mocha lodash chai proxyquire
```

launch test with
```
node node_modules/mocha/bin/_mocha --reporter spec demo.spec.js
```

The first test will pass if you remove the 'var doesNotExist = require('doesNotExist');' line.  However proxyquire doesn't seem to be able to override a module that isn't installed.  

Is this the intended functionality?  Did I miss some documentation?

**Comment by bendrucker** [comment]
This is expected behavior. proxyquire goes and gets the original so that your stub object only overrides the methods you specify and others work as expected. If you want to disable this, you can do so either per module or per proxyquire instance:

https://github.com/thlorenz/proxyquire#preventing-call-thru-to-original-dependency
