### ISSUE TITLE
Cant proxy when path is variable

### ISSUE THREAD

**Issue by doron2402** [thlorenz/proxyquire#70]
I'm using a variable (__BASE) for the root directory but seems like its not working.

Is there an easy fix for that?

that's working great:

```js
proxiedLocation = proxyquire(`${__BASE}/app/adapters/location`,{
    '../services/location': locationService
 });
```

but when I'm changing the `'../services/location'` to `__BASE + /app/services/location` or `SERVICE_LOCATON_PATH` or the es6 syntax its not working.

Thanks.

**Comment by bendrucker** [comment]
Please highlight your code and stick to ES5 so we can read it

**Comment by thlorenz** [comment]
Took care of the highlighting makes more sense now.
Please don't use `__BASE` variables. As you can see you're confusing yourself and others.
Just use relative paths.

FWIW proxyquire should be able to handle either just make sure that the strings that you use to replace modules are the exact same as how you are requireing them in the module you are testing.
I have a hunch you're using `__BASE` stuff in there as well so it's not the same string.

Push a sample to github that we can run simply via `npm install && npm test` and we may be able to help you more.

**Comment by doron2402** [comment]
@bendrucker es5 translation: 
when __BASE is global variable 
global.__BASE = __dirname inside index.js
var locationService = {
locationService.sayHi: function(){}
};
proxiedLocation = proxyquire(__BASE + '/app/adapters/location',{
    '../services/location': locationService
 });

**Comment by doron2402** [comment]
@thlorenz why not using global variable for path? its make life easier
all you need to do inside your index.js (first file that execute could be whatever) 
if (!global.__BASE) {
  global.__BASE = __dirname;
} 

then all over my code I can just
var userController = require(__BASE + '/controllers/users');

**Comment by bendrucker** [comment]
Again, please highlight your code. The reason to not do what you're doing is that your only valid JS file in your projects is your index file. Any other file can't be run on its own.
