### ISSUE TITLE
Cannot use with transpiled modules

### ISSUE THREAD

**Issue by vvo** [thlorenz/proxyquire#71]
Following #64, I still cannot use `babel-node test.js`, proxyquire will have no effect:

module.js
```js
var dep = require('dep');
console.log(dep);
```

test.js
```js
var proxyquire = require('proxyquire');
var mod = proxyquire('./module', {dep: function(){console.log('weee')}});
```

In a terminal:
```sh
babel-node test.js
# output contains the original dep
```

What can I do?

**Comment by thlorenz** [comment]
Please create a full sample project so we can have a look.
Set it up so we can clone it and then `npm install && npm test` to see the problem.

**Comment by vvo** [comment]
Dunno what happened, it works now.. mehhhh will reopen if it's redoing it again. Thanks
