### ISSUE TITLE
Paths passed to proxyquire must be relative to the file that actually required proxyquire, not to the currently executing test

### ISSUE THREAD

**Issue by epchris** [thlorenz/proxyquire#72]
In a lot of our tests we want to centralize test bootstrapping so we've put loading of proxyquire into a centralized bootstrap file.  So in a given test file this ends up looking like this (coffeescript):

`{proxyquire} = require '../helpers/bootstrap'`

When doing this , all of my calls to `proxyquire(...)` need to have the path relative to the bootstrap.coffee file and not the test file.

To test this, I removed the requiring of proxyquire from the bootstrap file into the test file itself and paths worked as expected.  I also moved the bootstrap file to a new directory and confirmed that I had to change all of my relative paths passed to the proxyquire call to be relative to the new bootstrap.

Any ideas as to why this might be happening or if there's a possible fix?

**Comment by bendrucker** [comment]
Nope, this is just the way requires work. They're always relative to the file in which they run.

**Comment by epchris** [comment]
@bendrucker I understand that the actual call to require is done in proxyquire, but why would it matter where proxyquire was originally required?  The call to `proxyquire('../../foo/bar')` is in the actual test itself and so I hoped the path would be relative to the test.  Thanks for taking the time to explain.

**Comment by bendrucker** [comment]
Think about this in plain Node terms — what you're basically doing is this:

```js
// a.js
module.exports = require
```

```js
// b.js
var getModuleViaA = require('./a')
getModuleViaA(/* ... */)
```

`require` is a special global that is localized to each module. You can pass it around, but it will always be bound to the module it was created for.

**Comment by sohale** [comment]
As a workaround, you can use module name with full absolute path in your calls to `proxyquire(...)`
