### ISSUE TITLE
undefined hasOwnProperty?

### ISSUE THREAD

**Issue by kkragenbrink** [thlorenz/proxyquire#73]
I'm a little baffled by this one, because hasOwnProperty is a part of node core. Using node-v0.12.7 and proxyquire-1.6.0.

```
/Users/kevin/Projects/omnisearch/node_modules/proxyquire/lib/proxyquire.js:117
    if (hasOwnProperty.call(stubs[key], '@global')) {
                       ^
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (native)
    at Proxyquire.load (/Users/kevin/Projects/omnisearch/node_modules/proxyquire/lib/proxyquire.js:117:24)
```

**Comment by thlorenz** [comment]
Looks like you passed `undefined` or `null` as stubs.
If you need more help, please push your code to github so we can just clone it and run `npm test` to see the problem.

**Comment by kkragenbrink** [comment]
Unfortunately this code is proprietary software and I cannot publish it anywhere.  I have double checked every call to proxyquire() that I've made, and in all of them, the second argument is a valid object.

**Comment by bendrucker** [comment]
It's not the object, it's the values:

https://github.com/thlorenz/proxyquire/blob/d96e4d8bcdce42cb997fed4172b869dbd9f7d7ee/lib/proxyquire.js#L115-L117

You must have a key that's `undefined` -- `null` is handled. Not a fan of taking undefined in order to indicate that a stub shouldn't be available, but we could throw when `undefined` shows up.

**Comment by bendrucker** [comment]
This is not a proxyquire bug but I opened #74 so the error is more helpful

**Comment by thlorenz** [comment]
LGTM please merge to master.
Also I added you as a collaborator on npm so now you can publish changes (I'm sure we agree on how to version things, so I'll leave that to you). i.e. this should be a minor upgrade IMO since it could break edge cases (not quite worth a major though).
