### ISSUE TITLE
react-dnd: Using Proxyquire to stub sub-components in unit tests results in test failure.

### ISSUE THREAD

**Issue by cmelion** [thlorenz/proxyquire#76]
Anyone run into this?
https://github.com/gaearon/react-dnd/issues/268
https://github.com/cmelion/react-hot-boilerplate/tree/Invariant-Violation-DND

**Comment by bendrucker** [comment]
Nope. If you can provide more info I can try to look into it. But I don't use React so I won't be able to help much unless you can offer some direction.

**Comment by bendrucker** [comment]
Didn't mean to close this. Happy to discuss but we do need more context (and not a link to a lengthy React-specific discussion).

**Comment by cmelion** [comment]
Hey Ben,
Thanks for responding.  This certainly isn't an issue with proxyquire and may not be a react-dnd problem either (it might be react contexts in general), I was just hoping someone using proxyquire had run into the problem and had a workaround.  Failing that, it seems useful to have some reference here for a solution once it is found, which does not require this issue to remain open.

As far as context, the linked repo demonstrates the issue.  Just run npm install, npm test.

A can say with certainty that proxyquire works fine for stubbing out react sub-components and even works for stubbing react-stores with react-DND context wrappers, just not with react DOM components.

**Comment by bendrucker** [comment]
Got it. If I can help explain how proxyquire accomplishes what it does, feel free to ask for clarification.

**Comment by cmelion** [comment]
The invariant violation goes away when I omit: "@global': true

Removing @global has the side-effect of breaking
 ```
TestUtils.findRenderedDOMComponentWithClass/Tag
```

**Comment by cmelion** [comment]
Issue resolved using:
        const subComponent = React.findDOMNode(comp).querySelectorAll('.simple-subcomponent');
        should(subComponent.length).equal(1);
