### ISSUE TITLE
Add documentation: Only works on functions

### ISSUE THREAD

**Issue by brycefisher** [thlorenz/proxyquire#80]
I've run into situations where I want to modify the global config object (which is basically just json). Proxyquire seems like an excellent tool for this, but after much trial and error I've come to the (correct?) conclusion that this module is only designed to work on replacing functions that are dependencies of a module, not values. It _might_ be helpful to document proxyquire doesn't change values for other wayward developers like myself (or maybe I'm alone in wanting to do this).

For posterity's sake, in node v0.10.x, you can modify values thusly:

```
require('your-module').value = 'STUB VALUE';
```

It looks odd, but it seems to work for me.

**Comment by bendrucker** [comment]
Can you share an example of something that's not working? Treating modules as mutable objects is definitely not a good idea.

**Comment by brycefisher** [comment]
I don't mean to get into a religious war -- I'm just trying to clearly understand and articulate the purpose of this module.

Am I correct to say that proxyquire does not let you stub values only functions?

**Comment by bendrucker** [comment]
Easiest way to discuss this is with code

**Comment by brycefisher** [comment]
@thlorenz am I correct to say that this module only replaces functions and not values? If so, could the documentation state that more clearly?

**Comment by bendrucker** [comment]
Proxyquire uses [fill-keys](https://github.com/bendrucker/fill-keys) to copy between objects and I'm not aware of any reason why anything else should behave differently. A failing test would be a huge help so I can run with this quickly and figure out what's up.

**Comment by brycefisher** [comment]
Gotcha -- let me see what I can do in that department.

What I was trying before was:

```
var config = proxyquire('/path/to/config'

**Comment by bendrucker** [comment]
Awesome -- doesn't need to be a true failing test PR, but just anything so that we're sure we're on the same page here.

**Comment by gyandeeps** [comment]
@brycefisher Can you try with this test code
```js
// foo_test.js
var foo = proxyquire('./foo', {
  config: { featureX: false, '@global': true }
});
assert(foo(), false); // Would actually return true
```

**Comment by bendrucker** [comment]
Any updates?

**Comment by brycefisher** [comment]
Ugh -- my bad! Sorry I got distracted over the weekend. Let me give this another go...

**Comment by bendrucker** [comment]
Awesome, thank you. #82 was the first proxyquire bug in quite a while so I'd love to track this down as well.

**Comment by LinusU** [comment]
I belive the problem to be that you pass `config` as the key but `foo.js` is requiring it as `./config`.

```diff
-   config: { featureX: false }
+   './config': { featureX: false }
```

**Comment by bendrucker** [comment]
Good eye @LinusU! If this is actually a pq issue we can reopen.

**Comment by mroderick** [comment]
I've created [a reduced test case](https://github.com/mroderick/proxyquire-issue-80) for this issue (or at least what I think is the same expectation not being met).

**Comment by bendrucker** [comment]
No, that's not a bug

> It shows that when a module exports an Object, that Object will have second argument to proxyquire merged into it and not be replaced by it.

That's a documented feature

**Comment by mroderick** [comment]
Cheers

**Comment by brycefisher** [comment]
Just to confirm, I can no longer reproduce this issue. I forked @mroderick 's repo here and made it closer to my examples above:
https://github.com/brycefisher/proxyquire-issue-80

The tests pass even without the `@global` flag... Thanks for your help in looking into this!
