### ISSUE TITLE
Loading C++ addon Node 0.12.2 Modules

### ISSUE THREAD

**Issue by sbowler** [thlorenz/proxyquire#83]
Hello,

It looks like we are having some problems trying to load a C++ addon built with Node 0.12.2. We have a module we are trying to proxyquire and it requires a C++ addon binary file for node. We get the error "Module did not self-register." on line 243 of proxyquire.js. 

It looks like your code is not compatible with this version of Node based on https://github.com/sass/node-sass/issues/653 which shows the same error and appears to be related to the version of Node. Would you be able to update your code to handle new versions of Node?

**Comment by thlorenz** [comment]
The error you're seeing is related to the module being incompatible with the version of node you're using.
Try the `.noCallThru` option and see if that works.
But since proxyquire doesn't do anything C++ related your problem couldn't be solved here afaik.

**Comment by sbowler** [comment]
I'm quite certain the module is built with the same version of node. It looks like the ```.noCallThru``` option is the way to go anyways. As you can imagine we aren't that concerned about unit testing the C++ addons. Thanks for the help.
