### ISSUE TITLE
Would it be possible to use `require.resolve`?

### ISSUE THREAD

**Issue by LinusU** [thlorenz/proxyquire#86]
One thing that is a bit of a gotcha, and also quite annoying in some situations, is that proxyquire requires you to know the exact string that the required module will use to require a mocked dependency.

Would it be possible to use `require.resolve` in order to use the canonical paths to the modules?

**Comment by bendrucker** [comment]
Not really possible. The algorithm requires checking the filesystem and falling back to a set of options in series. If the files in question don't actually exist, `require.resolve` can't help.

**Comment by LinusU** [comment]
But surely the files do exists? Otherwise it wouldn't function without the mocks?

**Comment by bendrucker** [comment]
Not necessarily. Proxyquire is happy to mock stuff for you that doesn't exist if you use `noCallThru`.

**Comment by LinusU** [comment]
Are you sure that we are talking about the same thing? I guess it's true that proxyquire could do that, but why would you ever want to? The file would then only be able to load with proxyrequire?

**a.js**
```javascript
var proxyrequire = require('proxyrequire')
var b = proxyrequire('./b', {
  './c': { msg: 'Hello' }
})

console.log(b.msg)
```

**b.js**
```javascript
exports.msg = require('./c').msg
```

```text
$ node a.js
Hello
$ node b.js
Error: ...
```

---

What I'm proposing is that this would work:

**test/basic.js**
```javascript
var parser = proxyquire('../lib/parser/api.js', {
  '../lib/lexer/api.js': mockLexer
})
```

Which it currently doesn't since the `lib/parser/api.js` file will make it includes as `../lexer/api.js'.

**Comment by bendrucker** [comment]
> I guess it's true that proxyquire could do that, but why would you ever want to? The file would then only be able to load with proxyrequire?

You'd want it if you were testing a scenario where some module were missing, either a relative path one or a node_modules one.

**Comment by LinusU** [comment]
Do you think that that scenario is more common than not knowing the exact string used in the other file? Maybe we could have it behind a function, like the `noCallThru`?

**Comment by bendrucker** [comment]
Not sure, but I don't like the idea of allowing you to specify files relative to the test file. It's confusing and likely breaking.
