### ISSUE TITLE
Documentation about caching behavior is very confusing

### ISSUE THREAD

**Issue by jmm** [thlorenz/proxyquire#91]
The documentation regarding caching behavior is very confusing, and in at least one case doesn't appear to be accurate. I created a [repro](https://github.com/jmm/proxyquire-cache-repro/commit/5c0be3609f1916d767a0cec8e08ce4dd761ef9fd) based on the [`preserveCache()` example from the `README`](https://github.com/thlorenz/proxyquire#forcing-proxyquire-to-reload-modules).

``` js
var assert = require("assert");
var stubs = {};

// ensure we don't get any module from the cache, but to load it fresh every time
var proxyquire = require('proxyquire').noPreserveCache();

proxyquire.preserveCache();

var foo1 = proxyquire('./foo', stubs);
var foo2 = proxyquire('./foo', stubs);
var foo3 = require('./foo');

// foo1, foo2 and foo3 are the same instance
assert.equal(foo1, foo2, "foo1 !== foo2");
assert.equal(foo1, foo3, "foo1 !== foo3");
```

Expected: Assertions pass.

Actual: First assertion fails.

When would `foo1` ever equal `foo2`? A quick glance at the code makes it seem that it wouldn't: https://github.com/thlorenz/proxyquire/blob/b9b47a48901059a411f0f88870009db9f03f02d2/lib/proxyquire.js#L133-L134

**Comment by thlorenz** [comment]
Any PR improving the docs is appreciated ;)

**Comment by jmm** [comment]
@thlorenz I had a feeling you'd say that :) TBH I'm struggling to understand what the intended behavior is at this point.

**Comment by thlorenz** [comment]
Sorry - swamped currently, maybe someone else can help.

**Comment by jmm** [comment]
@thlorenz Ok, thanks. I hope you don't mind leaving this open until it can get sorted out.

**Comment by thlorenz** [comment]
Yep, it's ok for now. Hopefully you won't have to wait too long to get some help.

**Comment by bendrucker** [comment]
The intended behavior is definitely to not have any of the foos strictly equal another. In theory you could check that the stubs were strictly equal or both empty and in that scenario return three identical references. I don't think it's worth implementing that behavior and getting that clever. Do you have any suggestions for where to include a mention in the docs so it's clear how/why the behavior is to not cache the return value?

**Comment by jmm** [comment]
@bendrucker Thanks for the reply. 

> Do you have any suggestions for where to include a mention in the docs so it's clear how/why the behavior is to not cache the return value?

I was going to ask if you can begin by summarizing what they're supposed to do. Otherwise I'd have to dig into the code to try to figure it out in the first place before I'd be able to correct the docs. Based on what you said it seems that the first assertion here would never pass, so that'd be a good place to start:

```js
proxyquire.preserveCache();

var foo1 = proxyquire('./foo', stubs);
var foo2 = proxyquire('./foo', stubs);
var foo3 = require('./foo');

// foo1, foo2 and foo3 are the same instance
assert.equal(foo1, foo2);
assert.equal(foo1, foo3);
```

I'm thinking now that these are supposed to be about clearing or leaving alone Node's regular `require()` cache (see also my updated [repro](https://github.com/jmm/proxyquire-cache-repro)):

```js
var proxyquire = require('proxyquire');

var foo1;
var foo2;

proxyquire.noPreserveCache();

foo1 = require("./foo");
proxyquire("./foo", stubs);
foo2 = require("./foo");

// With ordinary Node require() behavior these would be equal.
assert.notStrictEqual(foo1, foo2, "foo1 !== foo2");

proxyquire.preserveCache();

proxyquire("./foo", stubs);
foo1 = require("./foo");
assert.strictEqual(foo1, foo2, "foo1 === foo2");

```

Based on what you said it doesn't sound like successive calls to `proxyquire()` for the same target are ever supposed to return the same value. I'm thinking these options are supposed to address what's in the `require()` cache before and after calling proxyquire. I'm still not sure why the second assertion in the example at the top passes. It seems really counterintuitive. I'd have to dig into the code to figure out why and see if I can tell whether it's by design.

I haven't checked whether with `noPreserveCache` it clears the cache before or after stubbing it. I would think the point would be to clear it first. I think the point must be for a situation like singleton modules (i.e. so you get a fresh `items` each time):

```js
var items = [];

exports.items = items;

function add (item) {
  items.push(item);
}
```

**Comment by bendrucker** [comment]
In your second example the `noPreserveCache` option has to delete the module from the require cache. That's why the normal Node behavior is not observed there.

In the second case you've allowing the normal caching and so the normal behavior persists. Proxyquire does some magic where it clears and then repopulates the cache. The important thing here is that proxyquire is actually trying to clean up after itself and contain its effects. If you don't assign the result you should actually see exactly what you're getting there.
