### ISSUE TITLE
Proxyquire breaks code coverage with istanbul

### ISSUE THREAD

**Issue by Dakuan** [thlorenz/proxyquire#92]
Having some bother getting istanbul and proxyquire to play nicely.

If I import a module into my test normally:

``` es6
import subject from "../src/foo.es6"
```

Then istanbul covers the module as expected. 

Importing with proxyquire works, in that I can stub the things, but istanbul says that file is no longer covered, when it definitely is.

``` es6
let subject = proxyquire("../src/foo.es6", { /** stubs **/}).default;
```

**Comment by bendrucker** [comment]
Can you upload a minimal example? Eliminating all confounding factors (e.g. ES6) will help.

**Comment by osukaa** [comment]
I have this test with lab/code in Hapi and it's also telling me it's no longer with 100% code coverage. https://gist.github.com/osukaa/76468a57bd8e132d01b3

**Comment by bendrucker** [comment]
Same deal guys, it's gonna be a lot easier to look at this if we have something super simple that we can run directly versus having to set up everything.

**Comment by tjmehta** [comment]
Appears to break coverage reporting in lab as well: https://github.com/hapijs/lab/issues/505

**Comment by bendrucker** [comment]
Is it possible these tools depend on tracing `require` calls to work?

**Comment by tjmehta** [comment]
Actually yes, just found the problem. Will report back w/ fix for lab in 30. It appears the instrumentation logic resets global coverage variable anytime a "new" file is required. Proxyquire allows re-requiring of files (without using require cache), and lab's coverage instrumentation logic assumes each require is always of a new file.

**Comment by tjmehta** [comment]
The issue was within lab, not proxyquire. It assumed files could not be required multiple times.

https://github.com/tjmehta/lab/commit/1dea28808cb3d3603a34056f77d274cc4f5be8c0

**Comment by bendrucker** [comment]
Nice! Seems like the same situation might be happening for Istanbul as well. Closing this for now since it sounds like this needs to be addressed by the coverage tools rather than proxyquire.

**Comment by tjmehta** [comment]
Agreed :+1:

**Comment by bendrucker** [comment]
I'm more than happy to jump on an Istanbul thread if any context is needed. Fixing this won't be something I pursue myself for the same reason I didn't notice it: I don't use code coverage tools.
