### ISSUE TITLE
@runtimeGlobal blows out the stack

### ISSUE THREAD

**Issue by alexjeffburke** [thlorenz/proxyquire#93]
Hi there,

I know I'm probably pushing the limits of using proxyquire - I'm trying to mock a dependency all the way down. While I know that isn't recommended at all, it's likely the only way I can get the type of mocking working that I intend.

That being said I've hit a catch - if I enable @runtimeGlobal I very quickly seem to blow out the stack. I'm not entirely sure why that happens, presumably it's the constant invocation of the machinery that loads modules without caching. In any case, is there any means of mitigating this?

I was wondering if either there was a way of releasing the stack, or to mark a particular module as "i do want to make you swapped out even from runtime requires, but proxyquire is welcome to serve it up a previously loaded instance in that case"?

I have read the code a few times to see if that's possible, but the nature of this code and where it must run means the calling convention is extremely hairy. Side note, I'm actually in awe that this module actually exists and works so reliably!

Thanks in advance, AJB.

**Comment by bendrucker** [comment]
Can you offer a code example that we can run to reproduce this?

**Comment by alexjeffburke** [comment]
@bendrucker I'll see what I can do about a reduced test case.. the module I'm working on will be OSS but the codebase I tried it on wasn't quite :)

**Comment by bendrucker** [comment]
We can reopen this w/ an example

**Comment by jackwanders** [comment]
@bendrucker I'm not sure if this counts as an example worthy enough of reopening, but I just ran into the same issue.

For me, the cause appears to be a circular dependency within one of my own dependencies...in particular, `winston`. 

You can see a sub-module of `winston` requiring `winston` itself here:
https://github.com/winstonjs/winston/blob/master/lib/winston/container.js#L10

The dependency graph looks like:

```
─┬ winston.js
 └─┬ ./winston/container.js
   ─┬ ../winston.js
    └─┬ ./winston/container.js
      ─┬ ../winston.js
       └─┬ ./winston/container.js
         └ ... etc
```

This isn't a problem when the require cache is enabled, as the cache resolves the circular dependency without harm. However, `@runtimeGlobal` disables the cache, and `proxyquire` gets stuck in an infinite loop of requiring  a module, its children, then the module again, etc.

It seems that one way to resolve this would be for `proxyquire` to know whether or not the module sub-tree it's about to traverse 1) has already been resolved AND 2) contains no stubbed require paths. For example, if proxyquire knows that it has already loaded `winston` once, and that no stubbed paths exist within this sub-tree, it can safely retrieve `winston` from the require cache.

I'm not sure if this would *actually* work, or the best way to implement it, but I wanted to chime in and make you aware of a reproducible scenario for this issue.

**Comment by alexjeffburke** [comment]
@jackwanders You're description sounds incredibly familiar - I had a heavily instrumented proxyquire and it was definitely the cache being disabled when @runtimeGlobal enabled meant something was never taken from it. But you're summary of this is much better than mine.

I _think_ I experimented with trying to maintain the kind of thing you also suggested, like an internal visited dictionary where if a module was present in there it'd be returned from it - but it made me more in awe of the effort that went into getting this working because I just couldn't get it right and the issues it caused basically killed the module system.

Perhaps actually nailing this down would be possible with the better debugging tools that should be available in the form of v8-inspector in node 7.

**Comment by pagewang0** [comment]
@bendrucker require('winston') at @runtimeGlobal , because circular dependency +1
