### ISSUE TITLE
Prevent a dependency require/import

### ISSUE THREAD

**Issue by jithin1987** [thlorenz/proxyquire#94]
I have an es6 js file

```
import React from 'react';
import { FormattedNumber } from 'react-intl';


export default class ChartCircle extends React.Component {
  constructor(props) {
    super(props);
  }

```

And I am trying to request this file via proxyquire

```
var proxyquire = require('proxyquire').noCallThru();
let ChartCircle = proxyquire('../../../../src/components/metering/ChartCircle.js', {
  'react-intl': {
    FormattedNumber: function () {}
  }
});
```

But it's crashing with following error

```
Running "mochaTest:unit" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module 'react-intl'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (/Users/jithine/dev/simple/src/components/metering/ChartRadial.js:1:26)
>>     at Module._compile (module.js:460:26)
>>     at normalLoader (/Users/jithine/dev/simple/node_modules/babel-core/lib/api/register/node.js:199:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (/Users/jithine/dev/simple/node_modules/babel-core/lib/api/register/node.js:216:7)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
```

I don't have this dependency `react-int` installed at all, and I want proxyquire to mock this import. Will proxyquire work in this scenario ? Reason for not having this installed is this dependency is not handled by npm and is client only. But I want to unit test this and don't want to add this on my `devDependencies`

**Comment by bendrucker** [comment]
I assume this is compiled via Babel?

**Comment by jithin1987** [comment]
yes, I am using babel require hook.

**Comment by bendrucker** [comment]
https://github.com/bendrucker/proxyquire-issue-94

Test is passing above. Not sure what's up with your setup in particular. Babel might be screwing things up. If you can pare down what you've got and isolate the problem I can look further.

**Comment by jithin1987** [comment]
I will try to isolate it and provide an example, it could also be that I am using `system.js` which also deals with module imports.

**Comment by bendrucker** [comment]
I have a feeling it's got something to do with that. Let us know what you find, but for I think it's fair to say that proxyquire doesn't support other module systems. Only plain old `require`. We'd certainly consider a PR if you can figure out a simple fix for your setup.
