### ISSUE TITLE
Not stubbing our my own module correctly

### ISSUE THREAD

**Issue by PerfectSauce** [thlorenz/proxyquire#96]
Hi:
I am trying out proxyquire, but am having some issues.  I have tried the example to stub out require('os'), and it works, but I cannot stub out my own module.  Here is what I have:

realModule.js (this is my own module that I want to stub out)
    exports.get = function(id) {
	console.log("REAL get is called");
    }

moduleCaller.js:
    exports.callMe = function() {
	someModule.get(5);
    }

proxyTest.js (where I want to stub out realModule with my fakeModule):
    var proxyquire = require('proxyquire');
    var fakeModule= {
	get: function(id) {
		console.log("Fake get called");
	}
    };

    var test = proxyquire("./moduleCaller",{'someModule': fakeModule});
    test.callMe();  //always prints "REAL get is called"

Can you please help me to understand what I am missing?  Thanks!

**Comment by bendrucker** [comment]
`someModule` needs to be an exact path match for your module. Honestly having a super hard time understanding what you're doing because of the pseudocode and formatting. If you can spin up a quick standalone GH project I'd be more than happy to help.
