### ISSUE TITLE
stubbing require with dynamically generated path

### ISSUE THREAD

**Issue by hellboy81** [thlorenz/proxyquire#97]
How can I stub following require

```js
var myJSON = require(path.join(process.cwd(),'my.json'))
```

**Comment by thlorenz** [comment]
Figure out exactly what `path.join(process.cwd(),'my.json')` returns and use **exactly** that string as the _key_ for the stub.

However what you're doing is not recommended. Instead your `require` statements should always be relative to your modules, never to your working directory.
