### ISSUE TITLE
Calls the original function even though stubbing the original function using proxyquire

### ISSUE THREAD

**Issue by prajwal78** [thlorenz/proxyquire#98]
I have a module db.js which contains the following code:
```
var sql = require('mssql');
var async = require('async');

module.exports = {
    getDetails: function(number, callback) {

    async.parallel({
            general: function(callback) {
                getGeneral(number, callback);
            },
            preferences: function(callback) {
                getPref(number, callback);
            }
        },
        function(err, results) {
            if (err) {
                logger.error(err);
                throw err;
            }
            callback(results);
        });
}
};

function getGeneral(number, callback) {
    var mainconnection = new sql.Connection(dbCredentials[1].generalDBConfig, function(err) {
        var request = new sql.Request(mainconnection);
        request.input('number', sql.BigInt, number);
        request.execute('[number].[genral_get]', function(err, recordsets) {
            if (err) {
                logger.error(err);
            }
            var gen = {};
            var spResult = recordsets[0];
            if (spResult[0] != null) {
                spResult.forEach(function(record) {
                    var test = {};
                    gen[record.genCode] = record.genValue;
                });

                callback(null, gen);
            } else {
                callback(null, null);
            }

        });

    });
}

function getPref(number, callback) {
    var mainconnection = new sql.Connection(dbCredentials[0].prefDBConfig, function(err) {
        var request = new sql.Request(mainconnection);
        request.input('number', sql.BigInt, number);
        request.execute('[number].[pref_get]', function(err, recordsets) {
            if (err) {
                logger.error(err);
            }
            var spResult = recordsets[0];
            if (spResult[0] != null) {
                callback(null, spResult[0]);
            } else {
                callback(null, null);
            }

        });

    });
}
```

I have testfile testDB.js coantians following code:

```
require('mocha');

var chai = require('chai'),
    should = chai.should(),
    expect = chai.expect,
    assert = chai.assert,
    sinon = require('sinon'),
    proxyquire = require('proxyquire');

describe('Database Layer', function() {
    var stubs, number;

    before(function() {
        number = 72720604;

        stubs = {
            '../db': {
                getDetails: function(number, callback) {
                    var data = {
                        "general": {
                            "number": "72720604"
                            "title": "Mr  ",
                            "buildingNameNumber": null,
                            "subBuildingName": null,
                            "streetName": null,
                            "postalTown": null,
                            "county": null
                        },
                        "pref": {
                            "UseAccessibilitySite": "00000",
                            "IntroductorySource": "75"
                        }
                    };
                    callback(data);
                },
                '@noCallThru': false
            }
        };

        db = proxyquire('../db', stubs);

    });

    it('should return JSON data', function(done) {
        db.getDetails(number, function(err, data) {
            expect(err).to.be.null;
            expect(data).to.deep.equal({
                "number": "72720604"
            });
        })
    })



});
```

I am using mocha as test runner, chai as assertion library and proxyquire for overriding external dependencies. In the module db.js, there is a function getDetails that callbacks JSON data as specified in the variable stubs in testDB.js. getDetails function is internally calling SQL database operations. In the testfile testDB.js, I am stubbing the data returned from getDetails function in the variable stubs. I am unit testing getDetails function with assertion.

The problem is when I run the test, it is still calling the original function i.e.,trying to fetch the data from SQL database but which I don't want . For that reason, I have stubbed the data so that it doesn't perform any SQL operations. I want is to test the function getDetails with stubbed data but gives the following error: 

![fuera](https://cloud.githubusercontent.com/assets/10049692/11901170/2223e3ba-a5d0-11e5-94ea-0c7a177ac53d.png)

Any sort of help will be appreceiated!!!

**Comment by bendrucker** [comment]
That's not how proxyquire works. Proxyquire enables you to stub the dependencies of `db.js`, not mutate the file's own exports directly. I don't really understand what you're trying to do here either. What you're doing is effectively testing your mock rather than any of your source code.

**Comment by bendrucker** [comment]
Happy to help, but closing out since it's not a proxyquire bug/feature

**Comment by prajwal78** [comment]
How can I unit test the source code of db.js if I am testing my mock itself???

**Comment by bendrucker** [comment]
Proxyquire will help you mock the mssql package. If you can upload and example I can help further but it's gonna be too confusing to discuss what you have above without context.

**Comment by prajwal78** [comment]
I want to unit test the database layer of my restful API which I named it as db.js
```
var sql = require('mssql');
var async = require('async');

module.exports = {
    getDetails: function(number, callback) {

    async.parallel({
            general: function(callback) {
                getGeneral(number, callback);
            },
            preferences: function(callback) {
                getPref(number, callback);
            }
        },
        function(err, results) {
            if (err) {
                logger.error(err);
                throw err;
            }
            callback(results);
        });
}
};

function getGeneral(number, callback) {
    var mainconnection = new sql.Connection(dbCredentials[1].generalDBConfig, function(err) {
        var request = new sql.Request(mainconnection);
        request.input('number', sql.BigInt, number);
        request.execute('[number].[genral_get]', function(err, recordsets) {
            if (err) {
                logger.error(err);
            }
            var gen = {};
            var spResult = recordsets[0];
            if (spResult[0] != null) {
                spResult.forEach(function(record) {
                    var test = {};
                    gen[record.genCode] = record.genValue;
                });

                callback(null, gen);
            } else {
                callback(null, null);
            }

        });

    });
}

function getPref(number, callback) {
    var mainconnection = new sql.Connection(dbCredentials[0].prefDBConfig, function(err) {
        var request = new sql.Request(mainconnection);
        request.input('number', sql.BigInt, number);
        request.execute('[number].[pref_get]', function(err, recordsets) {
            if (err) {
                logger.error(err);
            }
            var spResult = recordsets[0];
            if (spResult[0] != null) {
                callback(null, spResult[0]);
            } else {
                callback(null, null);
            }

        });

    });
}
```

The file db.js has one function getDetails which in turns has two sub-functions i.e.,general and preferences. The two sub functions are in async.parallel mode so that it is operates parallely to fetch data from database for which it uses mssql package. The data returned from two sub functions are clubbed into one JSON format data i.e,
```
var data = {
                        "general": {
                            "number": "72720604"
                            "title": "Mr  ",
                            "buildingNameNumber": null,
                            "subBuildingName": null,
                            "streetName": null,
                            "postalTown": null,
                            "county": null
                        },
                        "pref": {
                            "UseAccessibilitySite": "00000",
                            "IntroductorySource": "75"
                        }
                    }
                }

```

I want to unit test the main function getDetails using mocha,chai and proxyquire in the database layer. As I am new to this unit testing methodologies putting me into haywire situation. Any sort help to unit this layer will be appreciated.

**Comment by bendrucker** [comment]
Same comment as above, please post this as a GH project and try to pare down the code so we can dig into the proxyquire side of things

**Comment by prajwal78** [comment]
ok I am putting it as gh project and share you the details...

**Comment by prajwal78** [comment]
Here is the link to the GH project: https://github.com/prajwal78/api.
There wouldn't be any SQL connectivity as the databases I located in my private cloud. The data returned from the database look like this as discussed earlier:
```
var data = {
                        "general": {
                            "number": "72720604"
                            "title": "Mr  ",
                            "buildingNameNumber": null,
                            "subBuildingName": null,
                            "streetName": null,
                            "postalTown": null,
                            "county": null
                        },
                        "pref": {
                            "UseAccessibilitySite": "00000",
                            "IntroductorySource": "75"
                        }
                    }
                }

```

Now, I think you can help me unit test this database layer. Please any sort of help is appreciated for a newbiee.

**Comment by bendrucker** [comment]
Still don't understand what you intend to test—`../db` is not a valid path

**Comment by prajwal78** [comment]
The pathto the db is ../repository/db.

**Comment by prajwal78** [comment]
I want to unit test db.js module which is the database layer of api. I want unit test function in different ways for db.js. lets say, the data returned is not null from the function. How can we mock sql?

**Comment by mkay581** [comment]
I may be a little late to the game and may even need to mind my own business but I think I understand what @prajwal78 is trying to say. He's trying to mock the methods that are exported from his own internal db.js file (hence the relative path name `./db`). 

But if I understand what you're saying, @bendrucker, you're saying that proxyquire cant stub out files relative to your project. You can only stub actual npm packages. Correct?

**Comment by bendrucker** [comment]
> But if I understand what you're saying, @bendrucker, you're saying that proxyquire cant stub out files relative to your project. You can only stub actual npm packages. Correct?

No not at all. You can totally test paths within your own project. The relative path given wasn't valid and we never came to an understanding on what the OP was trying to do.

**Comment by mkay581** [comment]
oh I was thrown off by your comment when you said:

> That's not how proxyquire works. Proxyquire enables you to stub the dependencies of db.js, not mutate the file's own exports directly.

Guess I misunderstood. Sorry about that. I've never used this package before so I was browsing through the issues.

**Comment by neoadventist** [comment]
@prajwal78 did you ever resolve your issue? Do you remember the _ah-ha_ moment when you got this to work?

**Comment by prajwal78** [comment]
@neoadventist Its been almost 2 years since I used proxyquire and it solved my problem. I don't remember exactly the details at the present moment. In the meanwhile, I will dig at my old projects where I used this package. It would be great if you could tell me what you want to solve.

**Comment by RenanSouza2** [comment]
If you ever find it will be helpfull, or at least post the correct syntax
